### ISSUE TITLE
Is v3 beta still alive? (React HMR in vite/rollup not working in v4 but working on v3 beta)

### ISSUE THREAD

**Issue by IgnusG** [callstack/linaria#1073]
## Environment

- Linaria version: 4.1.2
- Bundler (+ version): 3.1.4
- Node.js version: 18.9.0
- OS: Linux Arch

## Description

Running latest linaria with the react HMR plugin breaks with the following error:
```
11:43:59 PM [vite] Internal server error: Cannot use 'import.meta' outside a module in
| /linaria-hmr-repro/src/app.tsx

  Plugin: linaria
  File: /linaria-hmr-repro/src/app.tsx
      at /linaria-hmr-repro/node_modules/@linaria/babel-preset/lib/module.js:392:15
      at Array.forEach (<anonymous>)
      at Module.evaluate (/linaria-hmr-repro/node_modules/@linaria/babel-preset/lib/module.js:362:10)
      at evaluate (/linaria-hmr-repro/node_modules/@linaria/babel-preset/lib/evaluators/index.js:24:5)
      at evalStage (/linaria-hmr-repro/node_modules/@linaria/babel-preset/lib/transform-stages/2-eval.js:33:45)
      at syncStages (linaria-hmr-repro/node_modules/@linaria/babel-preset/lib/transform.js:54:45)
      at transform (/linaria-hmr-repro/node_modules/@linaria/babel-preset/lib/transform.js:147:10)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async TransformContext.transform (/linaria-hmr-repro/node_modules/@linaria/rollup/lib/index.js:75:22)
      at async Object.transform (file:///linaria-hmr-repro/node_modules/vite/dist/node/chunks/dep-6b3a5aff.js:41103:30)
      at async loadAndTransform (file:///linaria-hmr-repro/node_modules/vite/dist/node/chunks/dep-6b3a5aff.js:37365:29)
```

Additionally with the new JSX runtime the following error is thrown:

```
11:46:11 PM [vite] Internal server error: The argument 'path' must be a string or Uint8Array without null bytes. Received '\x00react/jsx-dev-runtime'
  Plugin: linaria
  File: /linaria-hmr-repro/src/app.tsx
      at Object.openSync (node:fs:591:10)
      at readFileSync (node:fs:467:35)
      at /linaria-hmr-repro/node_modules/@linaria/babel-preset/lib/transform-stages/1-prepare-for-eval.js:251:48
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async prepareForEval (/linaria-hmr-repro/node_modules/@linaria/babel-preset/lib/transform-stages/1-prepare-for-eval.js:226:24)
      at async Promise.all (index 0)
      at async prepareForEval (/linaria-hmr-repro/node_modules/@linaria/babel-preset/lib/transform-stages/1-prepare-for-eval.js:263:3)
      at async transform (/linaria-hmr-repro/node_modules/@linaria/babel-preset/lib/transform.js:141:31)
      at async TransformContext.transform (/linaria-hmr-repro/node_modules/@linaria/rollup/lib/index.js:75:22)
      at async Object.transform (file:///linaria-hmr-repro/node_modules/vite/dist/node/chunks/dep-6b3a5aff.js:41103:30)
      at async loadAndTransform (file:///linaria-hmr-repro/node_modules/vite/dist/node/chunks/dep-6b3a5aff.js:37365:29)
```

This curiously does not happen on the 3@beta branch but since we now have 4 as the latest major with active development, I'm not sure if 3@beta is still in development or not.

`@linaria/shaker` and `@linaria/rollup` both have a beta tag pointing to version [3.0.0-beta.23](https://www.npmjs.com/package/@linaria/rollup/v/3.0.0-beta.23) but `@linaria/core` does not have any beta tags anymore. Mixing the beta on the shaker and rollup with the latest on core also doesn't work.

## Reproducible Demo
https://github.com/IgnusG/linaria-hmr-repro

See the linaria 3@beta branch at https://github.com/IgnusG/linaria-hmr-repro/tree/linaria-3-beta

**Comment by IgnusG** [comment]
Thought I'd ping someone from the maintainers listening here (@Anber apologies for that, I see your name show in the releases on npm so I figured you could be the best fit).

> I would've tried the discord community but any answers would get lost there after some time

To also add a some more context to the original issue, I see that npm doesn't tag 3.x versions as beta under @linaria/core (anymore) but does under @linaria/rollup-plugin. Seems like a lot of installations also happen on those beta versions instead of the latest - maybe some more guidance around the version status would help there.

**Comment by Anber** [comment]
Hi @IgnusG 
`3.x` has been skipped because it was impossible to implement async resolvers from bundlers without significant changes in the code base. And those significant changes broke some things.
Thank you for the repo. I'll take a look later this week.

**Comment by Anber** [comment]
Well… It appeared that this issue actually was already fixed in https://github.com/callstack/linaria/pull/1084
