### ISSUE TITLE
`@linaria/babel-presets` throws error when evaluating code from `@storybook/instrumenter`

### ISSUE THREAD

**Issue by dlehmhus** [callstack/linaria#1113]
## Environment

- Linaria versions: 
	- 	 @linaria/core: 4.2.2,
	-    @linaria/react: 4.3.0,
	-    @linaria/webpack5-loader: 4.1.8,
- Bundler (+ version): Webpack 5.73.0
- Node.js version: 16.18.0
- OS: macOS Ventura 13.0.1

## Description

When using linaria functions `styled` or `css` in the same file as where you import `@storybook/testing-library` like this: 
```jsx
import React from 'react';
import { styled } from '@linaria/react';
import { within } from "@storybook/testing-library";

import { Button } from './Button';

export default {
  title: 'Example/Button',
  component: Button,
};

const Wrapper = styled.div`
  background: fuchsia;
`;

export const Primary = (args) => {
  return (
    <Wrapper>
      <Button {...args} />
    </Wrapper>
    )
};

Primary.play = async ({canvasElement}) => {
  const canvas = within(canvasElement);
  const button = canvas.getByRole('button');
  await expect(button).toBeInTheDocument();
};
```
`@linaria/babel-preset` throws an error while evaluating code: (this [file](https://github.dev/storybookjs/storybook/blob/82dc644bae8c9bdab8608caf33c8374a1a27b579/code/lib/instrumenter/src/instrumenter.ts#L614), to be specific)

```sh
13% building 1/14 entries 591/874 dependencies 19/241 modulesTypeError: Cannot read properties of undefined (reading 'location')
    at instrument (/Users/username/code/linaria-storybook/node_modules/@storybook/instrumenter/dist/esm/instrumenter.js:836:58)
    at /Users/username/code/linaria-storybook/node_modules/@storybook/testing-library/dist/esm/index.js:38:51
    at /Users/username/code/linaria-storybook/node_modules/@storybook/testing-library/dist/esm/index.js:215:3
    at Script.runInContext (node:vm:141:12)
    at /Users/username/code/linaria-storybook/node_modules/@linaria/babel-preset/lib/module.js:375:16
    at Array.forEach (<anonymous>)
    at Module.evaluate (/Users/username/code/linaria-storybook/node_modules/@linaria/babel-preset/lib/module.js:361:10)
    at require.Object.assign.ensure (/Users/username/code/linaria-storybook/node_modules/@linaria/babel-preset/lib/module.js:319:11)
    at /Users/username/code/linaria-storybook/src/stories/Button.stories.jsx:8:23
    at /Users/username/code/linaria-storybook/src/stories/Button.stories.jsx:58:3
ERR! => Failed to build the preview
ERR! Module build failed (from ./node_modules/@linaria/webpack5-loader/lib/index.js):
ERR! /Users/username/code/linaria-storybook/node_modules/@linaria/babel-preset/lib/module.js:391
ERR!         throw new EvalError(`${e.message} in${callstack.join('\n| ')}\n`);
ERR!         ^
ERR! 
ERR! EvalError: Cannot convert undefined or null to object in
ERR! | /Users/username/code/linaria-storybook/node_modules/@storybook/testing-library/dist/esm/index.js
ERR! | /Users/username/code/linaria-storybook/src/stories/Button.stories.jsx
ERR! 
ERR!     at /Users/username/code/linaria-storybook/node_modules/@linaria/babel-preset/lib/module.js:391:15
ERR!     at Array.forEach (<anonymous>)
ERR!     at Module.evaluate (/Users/username/code/linaria-storybook/node_modules/@linaria/babel-preset/lib/module.js:361:10)
ERR!     at require.Object.assign.ensure (/Users/username/code/linaria-storybook/node_modules/@linaria/babel-preset/lib/module.js:319:11)
ERR!     at /Users/username/code/linaria-storybook/src/stories/Button.stories.jsx:8:23
ERR!     at /Users/username/code/linaria-storybook/src/stories/Button.stories.jsx:58:3
ERR!     at Script.runInContext (node:vm:141:12)
ERR!     at /Users/username/code/linaria-storybook/node_modules/@linaria/babel-preset/lib/module.js:375:16
ERR!     at Array.forEach (<anonymous>)
ERR!     at Module.evaluate (/Users/username/code/linaria-storybook/node_modules/@linaria/babel-preset/lib/module.js:361:10)
ERR!     at evaluate (/Users/username/code/linaria-storybook/node_modules/@linaria/babel-preset/lib/evaluators/index.js:24:5)
ERR!     at evalStage (/Users/username/code/linaria-storybook/node_modules/@linaria/babel-preset/lib/transform-stages/2-eval.js:33:45)
ERR!     at syncStages (/Users/username/code/linaria-storybook/node_modules/@linaria/babel-preset/lib/transform.js:54:45)
ERR!     at transform (/Users/username/code/linaria-storybook/node_modules/@linaria/babel-preset/lib/transform.js:147:10)
ERR!     at runMicrotasks (<anonymous>)
ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

## Reproducible Demo

1. clone [repo](https://github.com/dlehmhus/linaria-storybook-bug-example)
2. `yarn install`
3. `yarn build-storybook`

**Comment by aspirisen** [comment]
This workaround helped https://github.com/storybookjs/storybook/issues/12782#issuecomment-1228557746

**Comment by dlehmhus** [comment]
Hey @aspirisen, could you elaborate on how that config helped you? For me, the config from the comment doesn't seem to work at all, unfortunately.  [See StackBlitz Example](https://stackblitz.com/edit/node-24zn2h?file=.storybook%2Fmain.js%3AL42).

**Comment by aspirisen** [comment]
hm, you are right, i just had the same error with storybook without `@storybook/testing-library` and thought the reason is the same

**Comment by layershifter** [comment]
@dlehmhus thanks for the repro, it works with `@linaria/webpack-loader@5.0.3`. Changes to make it working are in https://github.com/dlehmhus/linaria-storybook-bug-example/pull/1.
