### ISSUE TITLE
Invalid use of the "styled" tag

### ISSUE THREAD

**Issue by glassdimlygr** [callstack/linaria#1187]
## Environment

    Linaria version: 4.2.5
    Bundler (+ version): 5.75.0
    Node.js version: v16.14.2
    OS: MacOS
    react: 18.2.0
    @linaria/babel-preset: 4.2.4
    jest: 28.1.0

## Description
When I run nextjs or jest, I get an error with the linaria babel transformer.

```
 SyntaxError: /Users/myuser/www/rate.com/react-components/src/atoms/Tabs/Tabs.styles.ts: /Users/jjohn/www/rate.com/react-components/src/atoms/Tabs/Tabs.styles.ts: Invalid usage of `styled` tag
      1 | import { styled } from '@linaria/react';
      2 |
    > 3 | console.error({ styled });
        |                 ^^^^^^
      4 |
      5 | const ul = styled.ul;
      6 | // import getMediaQuery from '@tokens-src/utils-shared/getMediaQuery';

      at File.buildError [as buildCodeFrameError] (node_modules/jest-config/node_modules/@babel/core/src/transformation/file/file.ts:279:12)
      at NodePath.buildCodeFrameError (node_modules/@babel/traverse/src/path/index.ts:139:21)
      at buildCodeFrameError (node_modules/@linaria/babel-preset/src/utils/getTagProcessor.ts:60:17)
      at getTagProcessor (node_modules/@linaria/babel-preset/src/utils/getTagProcessor.ts:485:15)
      at processTemplateExpression (node_modules/@linaria/babel-preset/src/utils/processTemplateExpression.ts:22:24)
      at call (node_modules/@linaria/babel-preset/src/plugins/preeval.ts:86:11)
      at NodePath._call (node_modules/@babel/traverse/src/path/context.ts:34:20)
      at NodePath.call (node_modules/@babel/traverse/src/path/context.ts:19:17)
      at NodePath.visit (node_modules/@babel/traverse/src/path/context.ts:92:31)
      at TraversalContext.visitQueue (node_modules/@babel/traverse/src/context.ts:144:16)
      at TraversalContext.visitSingle (node_modules/@babel/traverse/src/context.ts:108:19)
      at TraversalContext.visit (node_modules/@babel/traverse/src/context.ts:176:19)
      at traverseNode (node_modules/@babel/traverse/src/traverse-node.ts:34:17)
      at NodePath.visit (node_modules/@babel/traverse/src/path/context.ts:99:33)
      at TraversalContext.visitQueue (node_modules/@babel/traverse/src/context.ts:144:16)
      at TraversalContext.visitMultiple (node_modules/@babel/traverse/src/context.ts:98:17)
      at TraversalContext.visit (node_modules/@babel/traverse/src/context.ts:174:19)
      at traverseNode (node_modules/@babel/traverse/src/traverse-node.ts:34:17)
      at NodePath.visit (node_modules/@babel/traverse/src/path/context.ts:99:33)
      at TraversalContext.visitQueue (node_modules/@babel/traverse/src/context.ts:144:16)
      at TraversalContext.visitMultiple (node_modules/@babel/traverse/src/context.ts:98:17)
      at TraversalContext.visit (node_modules/@babel/traverse/src/context.ts:174:19)
      at traverseNode (node_modules/@babel/traverse/src/traverse-node.ts:34:17)
      at NodePath.visit (node_modules/@babel/traverse/src/path/context.ts:99:33)
      at TraversalContext.visitQueue (node_modules/@babel/traverse/src/context.ts:144:16)
      at TraversalContext.visitSingle (node_modules/@babel/traverse/src/context.ts:108:19)
      at TraversalContext.visit (node_modules/@babel/traverse/src/context.ts:176:19)
      at traverseNode (node_modules/@babel/traverse/src/traverse-node.ts:34:17)
      at NodePath.visit (node_modules/@babel/traverse/src/path/context.ts:99:33)
      at TraversalContext.visitQueue (node_modules/@babel/traverse/src/context.ts:144:16)
      at TraversalContext.visitMultiple (node_modules/@babel/traverse/src/context.ts:98:17)
      at TraversalContext.visit (node_modules/@babel/traverse/src/context.ts:174:19)
      at traverseNode (node_modules/@babel/traverse/src/traverse-node.ts:34:17)
      at traverse (node_modules/@babel/traverse/src/index.ts:71:15)
      at NodePath.traverse (node_modules/@babel/traverse/src/path/index.ts:145:13)
      at PluginPass.call (node_modules/@linaria/babel-preset/src/plugins/preeval.ts:84:17)
          at transformFile.next (<anonymous>)
          at run.next (<anonymous>)
      at evaluateSync (node_modules/gensync/index.js:251:28)
      at fn (node_modules/gensync/index.js:89:14)
      at runPreevalStage (node_modules/@linaria/babel-preset/src/transform-stages/1-prepare-for-eval.ts:67:24)
      at prepareCode (node_modules/@linaria/babel-preset/src/transform-stages/1-prepare-for-eval.ts:133:30)
      at processQueueItem (node_modules/@linaria/babel-preset/src/transform-stages/1-prepare-for-eval.ts:239:45)
      at prepareForEvalSync (node_modules/@linaria/babel-preset/src/transform-stages/1-prepare-for-eval.ts:282:21)
```

My code looks like this: 
```
import { styled } from '@linaria/react';

// This errors... the import is broken. Not even undefined, totally broken. If this is removed, then it will error on `styled.ul`
console.error({ styled });

export const StyledTabs = styled.ul`
  display: flex;
  list-style: none;
`;

```

I attempted to resolve the path to the file manually w/ a custom tagResolver, made no difference. I can see the values to the files here and can `cat` them. Unfortunately this is not the problem.

linaria.config.js
```

const linariaConfig = {
  displayName: true,
  tagResolver: (source, tag) => {
    if (tag === 'css') {
      return require.resolve('@linaria/core/processors/css');
    }

    if (tag === 'styled') {
      console.error({ source, tag });
      console.error(require.resolve('@linaria/react/processors/styled'))
      return require.resolve('@linaria/react/processors/styled');
    }

    return null;
  }
};

module.exports = linariaConfig;

```

Here's my babel: 
```
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react",
    "@babel/preset-typescript",
    "@linaria"
  ],
  "plugins": [
    [
      "module-resolver"
    ],
    "babel-plugin-transform-typescript-metadata",
    ["@babel/plugin-proposal-decorators", { "legacy": true }]
  ]
}

```

## Reproducible Demo

To be honest, right now I'm feeling a bit frustrated and could use a little insight. I don't know how to tell you to replicate this because it makes no sense. My next step will be to try to replicate it in a separate repository.

**Comment by layershifter** [comment]
@glassdimlygr Please check the latest release, #1215 should fix it.

**Comment by layershifter** [comment]
This have been fixed, https://stackblitz.com/edit/stackblitz-starters-ueklne
