### ISSUE TITLE
Rollup builds are crashing on Windows/Linux

### ISSUE THREAD

**Issue by nstepien** [callstack/linaria#1206]
## Environment

- Linaria version: `babel-preset@4.4.1`, `rollup@4.3.4`
- Bundler (+ version): `rollup@3.14.0`
- Node.js version: 19.6.0
- OS: win11

## Description

In our [react-data-grid](https://github.com/adazzle/react-data-grid) repo, rollup builds crash when using the latest versions of linaria on Windows, so we had to pin to 1 month old versions.

Rollup does not crash in our CI (linux).
Webpack does not crash (either OS, `npm start`).

It might be a good idea to set up Windows CI in addition to Linux CI in the Linaria repo. 🤔 

## Reproducible Demo

- Clone https://github.com/adazzle/react-data-grid
- Checkout the `linaria-unpin` branch (see https://github.com/adazzle/react-data-grid/pull/3150)
- `npm i`
- `npm run build`

On Windows, this leads to the following build error:

```
./src/index.ts → ./lib/bundle.js, ./lib/bundle.cjs...
[!] (plugin linaria) SyntaxError: D:\repos\react-data-grid\src\GroupRow.tsx: The expression evaluated to 'undefined', which is probably a mistake. If you want it to be inserted into CSS, explicitly cast or transform the value to a string, e.g. - 'String(cell)'.
  34 |     }
  35 |
> 36 |     > .${cell}:not(:last-child):not(.${cellFrozenLast}) {
     |          ^^^^
  37 |       border-inline-end: none;
  38 |     }
  39 |   }
src/GroupRow.tsx
    at File.buildCodeFrameError (D:\repos\react-data-grid\node_modules\@babel\core\src\transformation\file\file.ts:279:12)
    at NodePath.buildError [as buildCodeFrameError] (D:\repos\react-data-grid\node_modules\@babel\traverse\src\path\index.ts:139:21)
    at buildCodeFrameError (D:\repos\react-data-grid\node_modules\@linaria\tags\src\utils\throwIfInvalid.ts:43:12)
    at templateProcessor (D:\repos\react-data-grid\node_modules\@linaria\tags\src\utils\templateProcessor.ts:74:19)
    at CssProcessor.build (D:\repos\react-data-grid\node_modules\@linaria\tags\src\TaggedTemplateProcessor.ts:37:39)
    at build (D:\repos\react-data-grid\node_modules\@linaria\babel-preset\src\plugins\collector.ts:33:23)
    at emit (D:\repos\react-data-grid\node_modules\@linaria\babel-preset\src\utils\processTemplateExpression.ts:29:3)
    at Identifier (D:\repos\react-data-grid\node_modules\@linaria\babel-preset\src\plugins\collector.ts:32:36)    
    at NodePath.call [as _call] (D:\repos\react-data-grid\node_modules\@babel\traverse\src\path\context.ts:34:20) 
    at NodePath._call [as call] (D:\repos\react-data-grid\node_modules\@babel\traverse\src\path\context.ts:19:17) 
    at NodePath.call [as visit] (D:\repos\react-data-grid\node_modules\@babel\traverse\src\path\context.ts:92:31) 
    at TraversalContext.visit [as visitQueue] (D:\repos\react-data-grid\node_modules\@babel\traverse\src\context.ts:144:16)
    at TraversalContext.visitQueue [as visitSingle] (D:\repos\react-data-grid\node_modules\@babel\traverse\src\context.ts:108:19)
    at TraversalContext.visitSingle [as visit] (D:\repos\react-data-grid\node_modules\@babel\traverse\src\context.ts:176:19)
    at visit (D:\repos\react-data-grid\node_modules\@babel\traverse\src\traverse-node.ts:34:17)
    at NodePath.visit (D:\repos\react-data-grid\node_modules\@babel\traverse\src\path\context.ts:99:33)
    at TraversalContext.visit [as visitQueue] (D:\repos\react-data-grid\node_modules\@babel\traverse\src\context.ts:144:16)
    at TraversalContext.visitQueue [as visitSingle] (D:\repos\react-data-grid\node_modules\@babel\traverse\src\context.ts:108:19)
    at TraversalContext.visitSingle [as visit] (D:\repos\react-data-grid\node_modules\@babel\traverse\src\context.ts:176:19)
    at visit (D:\repos\react-data-grid\node_modules\@babel\traverse\src\traverse-node.ts:34:17)
    at NodePath.visit (D:\repos\react-data-grid\node_modules\@babel\traverse\src\path\context.ts:99:33)
    at TraversalContext.visit [as visitQueue] (D:\repos\react-data-grid\node_modules\@babel\traverse\src\context.ts:144:16)
    at TraversalContext.visitQueue [as visitMultiple] (D:\repos\react-data-grid\node_modules\@babel\traverse\src\context.ts:98:17)
    at TraversalContext.visitMultiple [as visit] (D:\repos\react-data-grid\node_modules\@babel\traverse\src\context.ts:174:19)
    at visit (D:\repos\react-data-grid\node_modules\@babel\traverse\src\traverse-node.ts:34:17)
    at NodePath.visit (D:\repos\react-data-grid\node_modules\@babel\traverse\src\path\context.ts:99:33)
    at TraversalContext.visit [as visitQueue] (D:\repos\react-data-grid\node_modules\@babel\traverse\src\context.ts:144:16)
    at TraversalContext.visitQueue [as visitMultiple] (D:\repos\react-data-grid\node_modules\@babel\traverse\src\context.ts:98:17)
    at TraversalContext.visitMultiple [as visit] (D:\repos\react-data-grid\node_modules\@babel\traverse\src\context.ts:174:19)
    at visit (D:\repos\react-data-grid\node_modules\@babel\traverse\src\traverse-node.ts:34:17)
    at traverse (D:\repos\react-data-grid\node_modules\@babel\traverse\src\index.ts:71:15)
    at NodePath.traverse (D:\repos\react-data-grid\node_modules\@babel\traverse\src\path\index.ts:145:13)
    at PluginPass.traverse (D:\repos\react-data-grid\node_modules\@linaria\babel-preset\src\plugins\collector.ts:29:17)
    at call (D:\repos\react-data-grid\node_modules\@babel\core\src\transformation\index.ts:97:27)
    at transformFile.next (<anonymous>)
    at transformFile (D:\repos\react-data-grid\node_modules\@babel\core\src\transformation\index.ts:47:12)        
    at run.next (<anonymous>)
    at D:\repos\react-data-grid\node_modules\@babel\core\src\transform-ast.ts:34:20
    at Generator.next (<anonymous>)
    at evaluateSync (D:\repos\react-data-grid\node_modules\gensync\index.js:251:28)
    at sync (D:\repos\react-data-grid\node_modules\gensync\index.js:89:14)
    at fn (D:\repos\react-data-grid\node_modules\@babel\core\src\errors\rewrite-stack-trace.ts:97:14)
    at Object.transformFromAstSync (D:\repos\react-data-grid\node_modules\@babel\core\src\transform-ast.ts:77:59) 
    at transformFromAstSync (D:\repos\react-data-grid\node_modules\@linaria\babel-preset\src\transform-stages\3-prepare-for-runtime.ts:58:24)
    at syncStages (D:\repos\react-data-grid\node_modules\@linaria\babel-preset\src\transform.ts:65:47)
    at syncStages (D:\repos\react-data-grid\node_modules\@linaria\babel-preset\src\transform.ts:183:10)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.transform (file:///D:/repos/react-data-grid/node_modules/@linaria/rollup/src/index.ts:83:22)        
    at transform (D:\repos\react-data-grid\node_modules\rollup\dist\shared\rollup.js:23430:16)
    at ModuleLoader.addModuleSource (D:\repos\react-data-grid\node_modules\rollup\dist\shared\rollup.js:23636:30) 
```

**Comment by nstepien** [comment]
In this PR: https://github.com/adazzle/react-data-grid/pull/3150 linaria is now failing on linux too in CI, with the same error 🤔 
@Anber this is blocking us from adopting the latest version of linaria, and vitest 😭

**Comment by nstepien** [comment]
It seems like the culprit is that Linaria fails to extract the value from a re-exported variable, which itself is a class name generated by Linaria.
I've worked around it by skipping the re-export and importing directly from the original module.

**Comment by nstepien** [comment]
Nevermind, that fixed the issue in Rollup, but the same transpiling error happens occurs in Jest.

**Comment by nstepien** [comment]
With this change, the build doesn't crash anymore.

The output isn't correct though, obviously, but this may be a hint that there is a bug in the code cache handling.

```patch
diff --git a/packages/babel/src/cache.ts b/packages/babel/src/cache.ts
index e2b7992f..d42b096b 100644
--- a/packages/babel/src/cache.ts
+++ b/packages/babel/src/cache.ts
@@ -4,14 +4,7 @@ import type { ITransformFileResult } from './types';
 export class TransformCacheCollection {
   constructor(
     public readonly resolveCache: Map<string, string> = new Map(),
-    public readonly codeCache: Map<
-      string,
-      {
-        imports: Map<string, string[]> | null;
-        only: string[];
-        result: ITransformFileResult;
-      }
-    > = new Map(),
+    codeCache: Map<string, unknown> = new Map(),
     public readonly evalCache: Map<string, Module> = new Map()
   ) {}
+
+  get codeCache() {
+    return new Map<
+      string,
+      {
+        imports: Map<string, string[]> | null;
+        only: string[];
+        result: ITransformFileResult;
+      }
+    >();
+  }
 }
```

**Comment by nstepien** [comment]
We don't have this specific issue anymore.
