### ISSUE TITLE
Using css from linaria/core fails with an EvalError.

### ISSUE THREAD

**Issue by vamsiampolu** [callstack/linaria#1257]
## Environment

OS: OSX Ventura 13.3.1

node: v18.16.0
webpack: 5.86.0
babel: 7.22.1

---

@linaria/core: 4.2.10
@linaria/babel-preset: 4.4.5
@linaria/webpack-loader: 4.1.17

In my project, I attempt to create some global styles using:

```js
import React from "react";
import ReactDOM from "react-dom/client";
import { css } from "@linaria/core";

import "./styles.css";
import App from "./App";
import reportWebVitals from "./reportWebVitals";

const root = ReactDOM.createRoot(document.getElementById("root"));
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);

export const globals = css`
    .body {
      box-sizing: border-box;
    }
  }
`;
```

When I run `yarn start` which is `react-scripts start`, I see the error:

```
node_modules/@linaria/babel-preset/lib/module.js:355
      throw new EvalError(`${e.message} in${callstack.join('\n| ')}\n`);
      ^

EvalError: Cannot use import statement outside a module in
  node_modules/@babel/runtime/helpers/esm/interopRequireWildcard.js
| src/reportWebVitals.js
| src/index.js
```

The full error:

```
at Module.evaluate (tic-tac-toe/node_modules/@linaria/babel-preset/lib/module.js:355:13)
    at require.Object.assign.ensure (tic-tac-toe/node_modules/@linaria/babel-preset/lib/module.js:295:13)
    at tic-tac-toe/src/reportWebVitals.js:8:55
    at tic-tac-toe/src/reportWebVitals.js:29:3
    at Script.runInContext (node:vm:141:12)
    at Module.evaluate (tic-tac-toe/node_modules/@linaria/babel-preset/lib/module.js:342:14)
    at require.Object.assign.ensure (tic-tac-toe/node_modules/@linaria/babel-preset/lib/module.js:295:13)
    at tic-tac-toe/src/index.js:4:47
    at tic-tac-toe/src/index.js:12:3
    at Script.runInContext (node:vm:141:12)
    at Module.evaluate (tic-tac-toe/node_modules/@linaria/babel-preset/lib/module.js:342:14)
    at evaluate (tic-tac-toe/node_modules/@linaria/babel-preset/lib/evaluators/index.js:20:5)
    at evalStage (tic-tac-toe/node_modules/@linaria/babel-preset/lib/transform-stages/2-eval.js:26:45)
    at syncStages (tic-tac-toe/node_modules/@linaria/babel-preset/lib/transform.js:47:45)
    at transform (tic-tac-toe/node_modules/@linaria/babel-preset/lib/transform.js:146:10)
    at ./src/index.js (http://localhost:3000/static/js/bundle.js:9777:7)
    at options.factory (http://localhost:3000/static/js/bundle.js:10377:31)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:9835:33)
    at http://localhost:3000/static/js/bundle.js:10954:37
    at http://localhost:3000/static/js/bundle.js:10956:12
./src/index.js @ log.js:81
options.factory @ react refresh:6
__webpack_require__ @ bootstrap:24
(anonymous) @ startup:7
(anonymous) @ startup:7
```

## Reproducible Demo

https://github.com/vamsiampolu/tic-tac-toe-linaria

---

The issue does not occur when `import reportWebVitals from "./reportWebVitals";` is removed.

**Comment by vamsiampolu** [comment]
I think the issue is occuring because the linaria preset does not parse `import('web-vitals').then({ getCLS, ...other named imports})`, for example, the problem disappears when I use in `src/reportWebVitals.js`

```
import { getCLS, getFID, getFCP, getLCP, getTTFB } from "web-vitals";
```

When I do this, I can call:

```js
import { css } from '@linaria/core';
import reportWebVitals from './reportWebVitals';

css`
.body {
  ...css stuff
}
`

reportWebVitals();
```

Also found that placing:

```js
export const globals = css`
  :globals() {
    ...css stuff
  }
`;
```

fails to display anything.

**Comment by layershifter** [comment]
I checked out `master`, it works.

- I bumped to v5 that fixes a lot of bugs
- Tweaked `.babelrc` as Linaria also uses it for module evaluation
- Cleaned up dependencies

Changes are in the PR, https://github.com/vamsiampolu/tic-tac-toe-linaria/pull/1.

P.S. It's 2023, please don't use `create-react-app`.
