### ISSUE TITLE
Export default removing variable from scope

### ISSUE THREAD

**Issue by jpage-godaddy** [callstack/linaria#1272]
## Environment

- Linaria:
  * `@linaria/babel-preset@4.4.5`
  * `@linaria/cli@4.1.17`
  * `@linaria/shaker@4.2.11`
  * `@linaria/webpack-loader@4.1.17`
  * `@linaria/core@4.2.10`
  * `@linaria/react@4.3.8`
- Bundler: `webpack@5.88.1`
- Node.js version: `v18.16.0`
- OS: Linux

## Description

Linaria's JavaScript parser has a strange quirk where exporting a variable seemingly erases it from scope causing subsequent references to be undefined:

## Reproducible Demo

```javascript
export default function MyComponent() {
  // ...
}

MyComponent.propTypes = {
  foo: 'bar'
};
```

Error:

```
EvalError: MyComponent is not defined in
| /src/fake/path/my-component.js

    at Module.evaluate (.../node_modules/@linaria/babel-preset/lib/module.js:355:13)
    at evaluate (.../node_modules/@linaria/babel-preset/lib/evaluators/index.js:20:5)
    at evalStage (.../node_modules/@linaria/babel-preset/lib/transform-stages/2-eval.js:26:45)
    at syncStages (.../node_modules/@linaria/babel-preset/lib/transform.js:47:45)
    at transform (.../node_modules/@linaria/babel-preset/lib/transform.js:146:10)
    at async processFiles (.../node_modules/@linaria/cli/lib/linaria.js:114:9)
```

However, this works fine:

```javascript
function MyComponent() {
  // ...
}

MyComponent.propTypes = {
  foo: 'bar'
};

export default MyComponent;
```

**Comment by layershifter** [comment]
This was a problem with shaker. 

Have been fixed in v5, https://stackblitz.com/edit/stackblitz-starters-2zaqgy
