### ISSUE TITLE
.caller set but does not contain "name" property string

### ISSUE THREAD

**Issue by ntucker** [callstack/linaria#1290]
## Environment

- Linaria version: [4.5.2](https://renovatebot.com/diffs/npm/@linaria%2fcore/4.5.1/4.5.2)
- Bundler (+ version): webpack 5.88.2
- Node.js version: 20.2
- OS: Ubuntu

## Description

```bash
➤ YN0000: [example-linaria]: ERROR in ./src/index.tsx
➤ YN0000: [example-linaria]: Module build failed (from ../../node_modules/@linaria/webpack5-loader/lib/index.js):
➤ YN0000: [example-linaria]: Error: .caller set but does not contain "name" property string
➤ YN0000: [example-linaria]:     at Object.parseSync (/home/circleci/project/node_modules/@babel/core/lib/parse.js:41:72)
➤ YN0000: [example-linaria]:     at parseFile (/home/circleci/project/node_modules/@linaria/babel-preset/lib/transform-stages/helpers/parseFile.js:41:29)
➤ YN0000: [example-linaria]:     at processQueueItem (/home/circleci/project/node_modules/@linaria/babel-preset/lib/transform-stages/1-prepare-for-eval.js:97:38)
➤ YN0000: [example-linaria]:     at prepareForEval (/home/circleci/project/node_modules/@linaria/babel-preset/lib/transform-stages/1-prepare-for-eval.js:249:25)
➤ YN0000: [example-linaria]:     at transform (/home/circleci/project/node_modules/@linaria/babel-preset/lib/transform.js:143:65)
➤ YN0000: [example-linaria]:     at Object.webpack5LoaderPlugin (/home/circleci/project/node_modules/@linaria/webpack5-loader/lib/index.js:63:30)
➤ YN0000: [example-linaria]: 
➤ YN0000: [example-linaria]: webpack 5.88.2 compiled with 1 error in 567 ms
```

This started occuring only when trying to upgrade to 4.5.2 from 4.5.1

## Reproducible Demo

PR: https://github.com/ntucker/anansi/pull/2093

CI: https://app.circleci.com/pipelines/github/ntucker/anansi/9472/workflows/bcafc6ed-5dc2-483b-b3bf-dc49c974be60/jobs/50976

**Comment by Anber** [comment]
Hi, @ntucker!

The error says that the `caller` option in your Babel config doesn't have the required `name` field. It should be fixed in https://github.com/callstack/linaria/pull/1297, but I can't check it because package linking doesn't work between yarn and pnpm.

**Comment by ntucker** [comment]
@Anber If you release a new version we can check then

**Comment by Anber** [comment]
@ntucker released

**Comment by ntucker** [comment]
It worked!
