### ISSUE TITLE
EvalError: Cannot read properties of undefined (reading 'defineProperty')

### ISSUE THREAD

**Issue by ntucker** [callstack/linaria#1345]
## Environment

- Linaria version: 5.0.1
- Bundler (+ version): webpack 5.88.2
- Node.js version: stackblitz version?
- OS: webcontainers

## Description

```bash
ERROR in ./src/pages/Home/index.tsx
Module build failed (from ./node_modules/@linaria/webpack5-loader/lib/index.js):
EvalError: Cannot read properties of undefined (reading 'defineProperty') in/home/projects/reactive-data-client-mdzoyc/src/pages/Home/index.tsx

    at Module.evaluate (file:///home/projects/reactive-data-client-mdzoyc/node_modules/@linaria/babel-preset/lib/module.js:224:13)
    at evaluate (file:///home/projects/reactive-data-client-mdzoyc/node_modules/@linaria/babel-preset/lib/evaluators/index.js:15:5)
    at BaseAction.evalFile (file:///home/projects/reactive-data-client-mdzoyc/node_modules/@linaria/babel-preset/lib/transform/generators/evalFile.js:35:43)
    at evalFile.next (<anonymous>)
    at eval (file:///home/projects/reactive-data-client-mdzoyc/node_modules/@linaria/babel-preset/lib/transform/actions/BaseAction.js:66:78)
    at EventEmitter.action (file:///home/projects/reactive-data-client-mdzoyc/node_modules/@linaria/utils/lib/EventEmitter.js:25:22)
    at BaseAction.emitAction (file:///home/projects/reactive-data-client-mdzoyc/node_modules/@linaria/babel-preset/lib/transform/actions/BaseAction.js:131:39)
    at nextFn (file:///home/projects/reactive-data-client-mdzoyc/node_modules/@linaria/babel-preset/lib/transform/actions/BaseAction.js:66:32)
    at processNext (file:///home/projects/reactive-data-client-mdzoyc/node_modules/@linaria/babel-preset/lib/transform/actions/BaseAction.js:111:28)
    at Object.next (file:///home/projects/reactive-data-client-mdzoyc/node_modules/@linaria/babel-preset/lib/transform/actions/BaseAction.js:120:9)
```

## Reproducible Demo

https://stackblitz.com/edit/reactive-data-client-mdzoyc?file=src%2Fresources%2FTodoResource.ts,src%2Fpages%2FHome%2FTodoList.tsx

**Comment by layershifter** [comment]
Minimal repro: https://stackblitz.com/edit/stackblitz-starters-g4z8hc

**Comment by Anber** [comment]
It looks like the error appears only on Stackblitz. And the error itself is pretty wild because it says that `Object` in `Object. defineProperty` is not defined. Have you been able to reproduce it locally?

**Comment by layershifter** [comment]
> It looks like the error appears only on Stackblitz. And the error itself is pretty wild because it says that `Object` in `Object. defineProperty` is not defined. Have you been able to reproduce it locally?

The issue reproes only on Stackblitz and is specific to HappyDOM, the proposed fix is to use `GlobalWindow`. I will report the problem to upstream.

**Comment by layershifter** [comment]
Reported the issue, https://github.com/capricorn86/happy-dom/issues/1096
