### ISSUE TITLE
Build flaky with Typescript enum: throws EvalError not defined

### ISSUE THREAD

**Issue by PierreGUI** [callstack/linaria#1360]
## Environment
- Linaria version: 5.0.1
- Bundler (+ version): Webpack 5 (loader 5.0.2)
- Node.js version: 16.14.2
- OS: Mac OSX

## Description
Something is off with some enums. I use enums in many places, they mostly work fine. But in some cases the build fails on one of them:  
```
ERROR in ./src/components/clients/discover/Presenter.view.tsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
/node_modules/@linaria/babel-preset/lib/module.js:224
      throw new EvalError(`${e.message} in${this.callstack.join('\n| ')}\n`);
      ^

EvalError: ContentWidth is not defined in /src/constants/style.ts
```

Also, I call it flaky because this happened:
1. I encountered a similar error on my first build
2. I replaced with an object the `enum` which caused the error
3. Built sucessfully
4. Subsequent builds error on a different `enum` (see above)

This is `ContentWidth` from `/src/constants/style.ts`
```ts
export enum ContentWidth {
	xs = 360,
	sm = 540,
	md = 720,
	lg = 900,
	xl = 1140,
}
```

## Reproducible Demo
As I can't determine exactly how the problem occurs, I'll start with some debug logs:
```
2023-09-28T09:33:45.953Z linaria:transform:00026#1 >> evaluate __linariaPreval
2023-09-28T09:33:45.953Z linaria:transform:00026#1:module init /src/components/clients/pages/Checkout.tsx
2023-09-28T09:33:45.953Z linaria:cache:entrypoints get /src/components/clients/pages/Checkout.tsx hit
2023-09-28T09:33:45.953Z linaria:transform:00026#1 create EvaluatedEntrypoint for [ '__linariaPreval' ]
2023-09-28T09:33:45.953Z linaria:cache:entrypoints 00026:add /src/components/clients/pages/Checkout.tsx "updated"
2023-09-28T09:33:45.953Z linaria:transform:00026#1:module evaluate
2023-09-28T09:33:45.954Z linaria:transform:00026#1 set __linariaPreval: undefined
2023-09-28T09:33:45.954Z linaria:transform:00026#1:module require ../../../constants/style -> /src/constants/style.ts
2023-09-28T09:33:45.954Z linaria:cache:entrypoints get /src/constants/style.ts hit
2023-09-28T09:33:45.954Z linaria:transform:00026#1:module ✅ ready for evaluation
2023-09-28T09:33:45.954Z linaria:transform:00026#1->00046#3:module init /src/constants/style.ts
2023-09-28T09:33:45.954Z linaria:cache:entrypoints get /src/constants/style.ts hit
2023-09-28T09:33:45.954Z linaria:transform:00026#1->00046#3 create EvaluatedEntrypoint for [ 'Breakpoint', 'CHECKOUT_DUAL_BREAK_SIZE', 'CHECKOUT_WIDTH', 'ImageRatio' ]
2023-09-28T09:33:45.954Z linaria:cache:entrypoints 00046:add /src/constants/style.ts "updated"
2023-09-28T09:33:45.954Z linaria:transform:00026#1->00046#3:module evaluate
2023-09-28T09:33:45.954Z linaria:transform:00020#1->00046#1 set CHECKOUT_DUAL_BREAK_SIZE: undefined
2023-09-28T09:33:45.954Z linaria:transform:00020#1->00046#1 set CHECKOUT_WIDTH: undefined
2023-09-28T09:33:45.954Z linaria:transform:00020#1->00046#1 set Size: undefined
2023-09-28T09:33:45.954Z linaria:transform:00020#1->00046#1 set ZIndex: undefined
2023-09-28T09:33:45.954Z linaria:transform:00020#1->00046#1 set Size: { xs: 'xs', sm: 'sm', md: 'md', lg: 'lg', xl: 'xl', xxl: 'xxl' }
2023-09-28T09:33:45.954Z linaria:transform:00020#1->00046#1 set CHECKOUT_DUAL_BREAK_SIZE: 'md'
2023-09-28T09:33:45.955Z linaria:cache:entrypoints 00046:add /src/constants/style.ts "updated"
2023-09-28T09:33:45.955Z linaria:transform:00026#1->00046#3:module /src/constants/style.ts:37
const CHECKOUT_WIDTH = exports.CHECKOUT_WIDTH = ContentWidth.xs;
                                                ^

ReferenceError: ContentWidth is not defined
at /src/constants/style.ts:37:49
at /src/constants/style.ts:64:3
at Script.runInContext (node:vm:135:12)
at Module.evaluate (/node_modules/@linaria/babel-preset/lib/module.js:209:14)
at require.Object.assign.ensure (/node_modules/@linaria/babel-preset/lib/module.js:121:7)
at /src/components/clients/pages/Checkout.tsx:7:14
at /src/components/clients/pages/Checkout.tsx:65:3
at Script.runInContext (node:vm:135:12)
at Module.evaluate (/node_modules/@linaria/babel-preset/lib/module.js:209:14)
at evaluate (/node_modules/@linaria/babel-preset/lib/evaluators/index.js:15:5)
[
'/src/constants/style.ts',
'/src/components/clients/pages/Checkout.tsx'
]
2023-09-28T09:33:45.955Z linaria:cache:entrypoints 00026:add /src/components/clients/pages/Checkout.tsx "updated"
2023-09-28T09:33:45.955Z linaria:transform:00026#1:module /node_modules/@linaria/babel-preset/lib/module.js:224
  throw new EvalError(`${e.message} in${this.callstack.join('\n| ')}\n`);
  ^

EvalError: ContentWidth is not defined in/src/constants/style.ts
| /src/components/clients/pages/Checkout.tsx
```

None of the variables from this module should be undefined

**Comment by PierreGUI** [comment]
I just tried the new version and have the same error

**Comment by Anber** [comment]
Ok, thank you! Just wanted to be sure that this is not related to the bag with pluginOptions. We will take a look soon.

**Comment by PierreGUI** [comment]
FYI I fixed the error and got a successful build by replacing these 2 enums (out of 170 total) with their object+type counterpart.  I have no clue what makes these enums error in particular.

**Comment by PierreGUI** [comment]
Ok thanks I have the debug report I'll send it privately

**Comment by namoko** [comment]
Is there any update on this?
I have the similar problem, when migrating from Linaria 3 to 4 or 5 (Current version 5.0.2 core, 5.0.3 React)
