### ISSUE TITLE
`clsx` import breaks linaria

### ISSUE THREAD

**Issue by nstepien** [callstack/linaria#1367]
## Environment

- Linaria version: `@linaria/vite@5.0.3`
- Bundler (+ version): `vite@4.4.9`
- Node.js version: 20.8.0
- OS: win11, linux CI

## Description

Using the `clsx` package breaks linaria in vite builds.

```
> vite build

vite v4.4.9 building for production...
✓ 2 modules transformed.
✓ built in 288ms
[linaria] Unexpected token 'export' inD:/repos/vite-bug/node_modules/clsx/dist/clsx.mjs
| D:/repos/vite-bug/main.js

file: D:/repos/vite-bug/main.js
error during build:
D:\repos\vite-bug\node_modules\@linaria\babel-preset\lib\module.js:224
      throw new EvalError(`${e.message} in${this.callstack.join('\n| ')}\n`);
      ^

EvalError: Unexpected token 'export' inD:/repos/vite-bug/node_modules/clsx/dist/clsx.mjs
| D:/repos/vite-bug/main.js

    at Module.evaluate (D:\repos\vite-bug\node_modules\@linaria\babel-preset\lib\module.js:224:13)        
    at require.Object.assign.ensure (D:\repos\vite-bug\node_modules\@linaria\babel-preset\lib\module.js:118:7)
    at D:/repos/vite-bug/main.js:3:1
    at D:/repos/vite-bug/main.js:5:3
    at Script.runInContext (node:vm:134:12)
    at Module.evaluate (D:\repos\vite-bug\node_modules\@linaria\babel-preset\lib\module.js:209:14)        
    at evaluate (D:\repos\vite-bug\node_modules\@linaria\babel-preset\lib\evaluators\index.js:15:5)       
    at BaseAction.evalFile (D:\repos\vite-bug\node_modules\@linaria\babel-preset\lib\transform\generators\evalFile.js:35:43)
    at evalFile.next (<anonymous>)
    at D:\repos\vite-bug\node_modules\@linaria\babel-preset\lib\transform\actions\BaseAction.js:66:78     
    at EventEmitter.action (D:\repos\vite-bug\node_modules\@linaria\utils\lib\EventEmitter.js:25:22)      
    at BaseAction.emitAction (D:\repos\vite-bug\node_modules\@linaria\babel-preset\lib\transform\actions\BaseAction.js:131:39)
    at nextFn (D:\repos\vite-bug\node_modules\@linaria\babel-preset\lib\transform\actions\BaseAction.js:66:32)
    at processNext (D:\repos\vite-bug\node_modules\@linaria\babel-preset\lib\transform\actions\BaseAction.js:111:28)
    at Object.next (D:\repos\vite-bug\node_modules\@linaria\babel-preset\lib\transform\actions\BaseAction.js:120:9)
    at asyncActionRunner (D:\repos\vite-bug\node_modules\@linaria\babel-preset\lib\transform\actions\actionRunner.js:39:102)
    at async asyncActionRunner (D:\repos\vite-bug\node_modules\@linaria\babel-preset\lib\transform\actions\actionRunner.js:46:22)
    at async transform (D:\repos\vite-bug\node_modules\@linaria\babel-preset\lib\transform.js:107:20)     
    at async Object.transform (D:\repos\vite-bug\node_modules\@linaria\vite\dist\index.js:135:22)
    at async transform (file:///D:/repos/vite-bug/node_modules/rollup/dist/es/shared/node-entry.js:24449:16)
    at async ModuleLoader.addModuleSource (file:///D:/repos/vite-bug/node_modules/rollup/dist/es/shared/node-entry.js:24649:30)
```

## Reproducible Demo

This is enough to break linaria:
```js
import 'clsx';
```

https://github.com/nstepien/vite-bug/tree/lin-clsx

1. Clone the repo and checkout the `lin-clsx` branch
1. `npm ci`
1. `npm run build`

**Comment by layershifter** [comment]
@nstepien thanks for reporting, it's a valid bug. @Anber the "export issue" strikes again.

`clxs` is resolved to `node_modules/clsx/dist/clsx.mjs`, while `clsx.mjs` contains minified code in a single string that ends with:

```js
n+=t);return n}export default clsx;
```

And it not handled by a regex there:
https://github.com/callstack/linaria/blob/a6a15b919b82dde10a2a2409a6a03a5eaa938267/packages/babel/src/transform/helpers/loadLinariaOptions.ts#L79-L80

**Comment by Anber** [comment]
🤦‍♂️

**Comment by nstepien** [comment]
Hoping for a new release soon 🙏🥺

**Comment by nstepien** [comment]
Still no release? ⏳
