### ISSUE TITLE
Filter unhelpful babel stack traces from code frames

### ISSUE THREAD

**Issue by thymikee** [callstack/linaria#156]
**Do you want to request a *feature* or report a *bug*?**
Enhancement

**What is the current behavior?**
Here's one of our snapshots for the error:
```
<<CWD>>/node_modules/babel-core/lib/transformation/file/index.js:590
      throw err;
      ^

SyntaxError: test.js: Couldn't determine the class name for CSS template literal. Ensure that it's either:
- Assigned to a variable
- Is an object property
- Is a prop in a JSX element

  1 | import css from '<<CWD>>/build/css.js';
  2 | 
> 3 |     css\`
    |     ^
  4 | font-size: 3em;
  5 | \`;
    at File.buildCodeFrameError (<<CWD>>/node_modules/babel-core/lib/transformation/file/index.js:427:15)
    at NodePath.buildCodeFrameError (<<CWD>>/node_modules/babel-traverse/lib/path/index.js:140:26)
    at PluginPass.TaggedTemplateExpression (<<CWD>>/build/babel/preval-extract/index.js:106:24)
    at newFn (<<CWD>>/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (<<CWD>>/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (<<CWD>>/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (<<CWD>>/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (<<CWD>>/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (<<CWD>>/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (<<CWD>>/node_modules/babel-traverse/lib/context.js:192:19)
```

**What is the expected behavior?**
There's a lot of unnecessary noice which could be filtered out. I think this would be more helpful:
```
<<CWD>>/node_modules/babel-core/lib/transformation/file/index.js:590
      throw err;
      ^

SyntaxError: test.js: Couldn't determine the class name for CSS template literal. Ensure that it's either:
- Assigned to a variable
- Is an object property
- Is a prop in a JSX element

  1 | import css from '<<CWD>>/build/css.js';
  2 | 
> 3 |     css\`
    |     ^
  4 | font-size: 3em;
  5 | \`;

    at PluginPass.TaggedTemplateExpression (<<CWD>>/build/babel/preval-extract/index.js:106:24)
```

**Comment by thymikee** [comment]
Not relevant for now.
