### ISSUE TITLE
Cannot resolve imports of e.g. .tsx files when not specifing extenion explicitly

### ISSUE THREAD

**Issue by radoslaw-medryk** [callstack/linaria#282]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Bug is related to projects using non-default extensions for component files (e.g. `.ts`, `.tsx`).
That means it is likely to occur in projects using TypeScript.

Problem occures when importing a file *from inside of a file that uses linaria*, where *extension of imported file is not specified* but is left for webpack to resolve using `resolve.extensions` setting in *webpack config*, and extension is *not one of resolved by default* (`.js`, `.jsx`).

e.g.
```typescript
import { FullScreen } from "./FullScreen"; // where file name is e.g. `Component.tsx`
```

Build process fails with error similar to:
```
Error: Cannot find module './FullScreen'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Module.resolve (/home/user/git/@radoslaw-medryk/linaria-example/node_modules/linaria/lib/babel/module.js:79:27)
    at Module.require (/home/user/git/@radoslaw-medryk/linaria-example/node_modules/linaria/lib/babel/module.js:87:27)
```

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**

Reproducing example is **in branch** `bug/import_extensions` at: https://github.com/radoslaw-medryk/linaria-example

Reporducing steps:
- `npm install`
- `npm run start`
- Get build error similar to one mentioned above.

**What is the expected behavior?**
linaria should be able to handle the same extensions as webpack build process can.

**Please provide your exact Babel configuration and mention your Linaria, Node, Yarn/npm version and operating system.**

`linaria@1.0.0-beta.1`
`webpack@4.24.0`

webpack.config.js:
```javascript
{
// (...)

resolve: {
    extensions: [".ts", ".tsx", ".js", ".json"]
},

// (...)
}
```

**Comment by radoslaw-medryk** [comment]
I can look into it later and try to come up with PR with fix.

**Comment by radoslaw-medryk** [comment]
Seems to be fixed by https://github.com/callstack/linaria/pull/283 .
