### ISSUE TITLE
Jest coverage don't work with component interpolation

### ISSUE THREAD

**Issue by swa1ps** [callstack/linaria#321]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When I run test without coverage, then all is ok, but with coverage flag I have this error:

```sh
> cross-env NODE_ENV=test jest --coverage

 FAIL  src/Button/Button.test.js
  ● Test suite failed to run

    SyntaxError: <...>/src/Button/Button.js: An error occurred when evaluating the expression: cov_wch69k2u2 is not defined. Make sure you are not using a browser or Node specific API.
      22 |   border: 1px solid ${defaultColor};
      23 |
    > 24 |   &:hover ${Icon}{
         |             ^
      25 |     color: blue;
      26 |   }
      27 | `;

      at File.buildCodeFrameError (node_modules/@babel/core/lib/transformation/file/file.js:261:12)
      at NodePath.buildCodeFrameError (node_modules/@babel/traverse/lib/path/index.js:157:21)
      at buildCodeFrameError (node_modules/linaria/src/babel/extract.js:430:28)
          at Array.forEach (<anonymous>)
      at PluginPass.forEach (node_modules/linaria/src/babel/extract.js:354:22)
      at newFn (node_modules/@babel/traverse/lib/visitors.js:193:21)
      at NodePath._call (node_modules/@babel/traverse/lib/path/context.js:53:20)
      at NodePath.call (node_modules/@babel/traverse/lib/path/context.js:40:17)
      at NodePath.visit (node_modules/@babel/traverse/lib/path/context.js:88:12)
      at TraversalContext.visitQueue (node_modules/@babel/traverse/lib/context.js:118:16)
```

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**

```sh
git clone git@github.com:swa1ps/hello-linaria.git
cd hello-linaria
npm run test:coverage
```

**What is the expected behavior?**

Button test should be success passed

**Please provide your exact Babel configuration and mention your Linaria, Node, Yarn/npm version and operating system.**

**babel.config.js**
```js
module.exports = {
  presets: [
    '@babel/react',
    [
      '@babel/env',
      {
        targets: {
          browsers: [
            '>0.25%',
            'not op_mini all'
          ]
        },
        modules: false
      } 
    ],
    'linaria/babel'
  ],
  env: {
    test: {
      presets: [
        '@babel/react',
        ['@babel/env', { modules: 'commonjs' }],
      ],
      plugins: [
        '@babel/plugin-transform-modules-commonjs',
      ],
    }
  }
}
```

**linaria.config.js**
```js
module.exports = {
  evaluate: true,
  displayName: true,
}
```

```
linaria v1.1.4
node v10.14.1
npm v6.4.1
macOS Mojave v10.14.2
```

**Comment by satya164** [comment]
Thanks for reporting. We'll take a look

**Comment by kojidev** [comment]
Sorry for necroposting but I'm still experiencing this:
```
const colorRed = 'red';
const colorRedCode = '#ff4a4c';

const colorBlue = 'blue';
const colorBlueCode = '#037ff9';

const styleOutline = 'outline';
const styleSolid = 'solid';

function outlineButton(color: string) {
  return `
    border-color: ${color};
    color: ${color};
    background: white;
  `;
}

function solidButton(color: string) {
  return `
    color: white;
    border-color: ${color};
    background: ${color};
  `;
}

export const cnButtonStyles = {
  [styleOutline]: {
    [colorRed]: css`
      ${outlineButton(colorRedCode)}
    `,
    [colorBlue]: css`
      ${outlineButton(colorBlueCode)}
    `
  },
  [styleSolid]: {
    [colorRed]: css`
      ${solidButton(colorRedCode)}
    `,
    [colorBlue]: css`
      ${solidButton(colorBlueCode)}
    `
  }
};
```

```
SyntaxError: path/src/ui/Button/Button.styles.ts: An error occurred when evaluating the expression: 

      > cov_2qgro618ay is not defined. 

      Make sure you are not using a browser or Node specific API and all the variables are available in static context.
      Linaria have to extract pieces of your code to resolve the interpolated values.
      Defining styled component or class will not work inside:
        - function,
        - class,
        - method,
        - loop,
      because it cannot be statically determined in which context you use them.
      That's why some variables may be not defined during evaluation.
          
      52 |   [styleOutline]: {
      53 |     [colorRed]: css`
    > 54 |       ${outlineButton(colorRedCode)}
         |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

it works fine without coverage

**Comment by kojidev** [comment]
jest? puts cov_* variables to beginning of function declarations if you move functions outside of style file and import them, or just ignore coverage from style files altogether

**Comment by jpnelson** [comment]
We still saw this too. I think there might be a different, additional problem of the same type. We fixed it with changing our babel config (just in a test [env](https://stackoverflow.com/questions/34924581/how-do-you-configure-babel-to-run-with-different-configurations-in-different-env) ) to:

```
"test": {
      // We transform our test files before we run them via Bazel & Jest. In order for the
      // tests to run in a JSDOM environment correctly, we need to preserve environment pragma comments here.
      "comments": true,
      "presets": [
        [
          "@babel/preset-env",
          {
            "targets": {
              "node": true,
            },
            "modules": false,

            // https://babeljs.io/docs/en/babel-preset-env#bugfixes
            "bugfixes": true,
          },
        ],

        // https://github.com/callstack/linaria/issues/438
        [
          "@linaria",
          {
            "classNameSlug": "[title]",

            // There's an issue with jest / linaria integration regarding code
            // coverage. To reproduce the issue, you can run tests locally with
            // coverage and you'll see an
            // error like: `cov_2qgro618ay is not defined.` The problem is that
            // files get transformed by jest when they're run, to insert these
            // coverage counters (cov_*). If we don't also run
            // babel-plugin-istanbul over files before evaluating dependencies,
            // we get the transformed files, but no definitions for the
            // instrumentation. Adding babel-plugin-istanbul should make
            // linaria's evaluation and what jest is doing equivalent
            // https://github.com/callstack/linaria/issues/321
            "babelOptions": {
              "plugins": [
                "babel-plugin-istanbul",
              ],
            },
          },
        ],
      ],
    }
```
