### ISSUE TITLE
Issue with Imported Values Using Gatsby Plugin

### ISSUE THREAD

**Issue by mattoni** [callstack/linaria#404]
## Environment
Using Gatsby plugin + linaria.config.js file

linaria.config.js:
```
module.exports = {
  evaluate: true,
};

```

## Description

I'm attempting to import an object of colors from an external UI  library in node_modules (bundled with rollup, just in case it matters). I get the following error: 

```
ERROR in ./src/components/docs/Article.tsx
Module build failed (from ./node_modules/linaria/loader.js):
SyntaxError: /mnt/c/Users/matto/Documents/Development/cycle/documentation/src/components/docs/Article.tsx: An error occurred when evaluating the expression: Unexpected token {. Make sure you are not using a browser or Node specific API.
  36 |         top: 1.4rem;
  37 |         border-radius: 50%;
> 38 |         background-color: ${BColors.BLUE_ACCENT};
     |                             ^
  39 |       }
  40 |     }
  41 |   }
    at File.buildCodeFrameError (/mnt/c/Users/matto/Documents/Development/cycle/documentation/node_modules/@babel/core/lib/transformation/file/file.js:261:12)
    at NodePath.buildCodeFrameError (/mnt/c/Users/matto/Documents/Development/cycle/documentation/node_modules/@babel/traverse/lib/path/index.js:157:21)
    at /mnt/c/Users/matto/Documents/Development/cycle/documentation/node_modules/linaria/lib/babel/visitors/TaggedTemplateExpression.js:200:22
    at Array.forEach (<anonymous>)
    at TaggedTemplateExpression (/mnt/c/Users/matto/Documents/Development/cycle/documentation/node_modules/linaria/lib/babel/visitors/TaggedTemplateExpression.js:127:16)
    at TaggedTemplateExpression (/mnt/c/Users/matto/Documents/Development/cycle/documentation/node_modules/linaria/lib/babel/extract.js:28:61)
    at NodePath._call (/mnt/c/Users/matto/Documents/Development/cycle/documentation/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/mnt/c/Users/matto/Documents/Development/cycle/documentation/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/mnt/c/Users/matto/Documents/Development/cycle/documentation/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/mnt/c/Users/matto/Documents/Development/cycle/documentation/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/mnt/c/Users/matto/Documents/Development/cycle/documentation/node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (/mnt/c/Users/matto/Documents/Development/cycle/documentation/node_modules/@babel/traverse/lib/context.js:146:19)
    at Function.traverse.node (/mnt/c/Users/matto/Documents/Development/cycle/documentation/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/mnt/c/Users/matto/Documents/Development/cycle/documentation/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/mnt/c/Users/matto/Documents/Development/cycle/documentation/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitMultiple (/mnt/c/Users/matto/Documents/Development/cycle/documentation/node_modules/@babel/traverse/lib/context.js:85:17)
    at TraversalContext.visit (/mnt/c/Users/matto/Documents/Development/cycle/documentation/node_modules/@babel/traverse/lib/context.js:144:19)
    at Function.traverse.node (/mnt/c/Users/matto/Documents/Development/cycle/documentation/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/mnt/c/Users/matto/Documents/Development/cycle/documentation/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/mnt/c/Users/matto/Documents/Development/cycle/documentation/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitMultiple (/mnt/c/Users/matto/Documents/Development/cycle/documentation/node_modules/@babel/traverse/lib/context.js:85:17)
    at TraversalContext.visit (/mnt/c/Users/matto/Documents/Development/cycle/documentation/node_modules/@babel/traverse/lib/context.js:144:19)
 @ ./src/components/docs/index.ts 1:0-26 1:0-26
 @ ./src/pages/hubs/members-&-permissions/roles-and-permissions.tsx
 @ ./.cache/sync-requires.js
 @ ./.cache/app.js
 @ multi event-source-polyfill (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false ./.cache/app
ℹ ｢wdm｣: Failed to compile.
```

If I import the colors from the local directory,  they work so I thought it was an issue with the "evaluate" option, but enabling that doesn't seem to help. The object I'm trying to import is as follows:

```
export const BColors = {
  BLUE: `rgb(74, 157, 215)`,
  BLUE_ACCENT: `rgb(68, 151, 209)`,
}
```

Really excited about using linaria exclusively, just hitting a couple roadblocks that might end up being good for documentation later if it's a simple misconfiguration. Thanks in advance for the help.

**Comment by pbitkowski** [comment]
You need to whitelist that library, please check our docs for ignore option: 
https://github.com/callstack/linaria/blob/master/docs/CONFIGURATION.md#options

**Comment by failpunk** [comment]
@pbitkowski What library are you referring to in this example?
