### ISSUE TITLE
Update: babel to 7.4

### ISSUE THREAD

**Issue by Hotell** [callstack/linaria#407]
## Environment

```
linaria@1.3.1
@babel/core@7.4.4
@babel/cli@7.4.4
```

## Description

**Related** https://github.com/babel/babel/issues/9910

There was an issue within babel core with `as const` in TypeScript, which was resolved in babel 7.4. Linaria CLI uses old `7.3.3` as dependency. 

## Reproducible Demo

```sh
lerna exec --scope @twisto/theme -- 'linaria --config $LERNA_ROOT_PATH/linaria.config.js --out-dir dist/styles \"src/**/*.tsx\" \"src/**/*.ts\"'
```

will throw because theme package contains  `as const`

```ts
export const createAnimation = <T extends string>(
  name: T,
  definition: { [percentage: string]: CSSProperties }
) => {
  const animationDef = `@keyframe ${name} { ${createCssDefinitionFromObject(
    definition
  )} }`

  return {
    name,
    definition: animationDef,
  } as const
```

**Error:**

```
lerna exec --scope @twisto/theme -- 'linaria --config $LERNA_ROOT_PATH/linaria.config.js --out-dir dist/styles "src/**/*.tsx" "src/**/*.ts"'
lerna notice cli v3.13.4
lerna info versioning independent
lerna info filter [ '@twisto/theme' ]
lerna info Executing command in 1 package: "linaria --config $LERNA_ROOT_PATH/linaria.config.js --out-dir dist/styles \"src/**/*.tsx\" \"src/**/*.ts\""
/Users/hotell/Projects/devel/twisto/twisto-ui/node_modules/linaria/node_modules/@babel/core/lib/transformation/normalize-file.js:209
    throw err;
    ^

SyntaxError: /Users/hotell/Projects/devel/twisto/twisto-ui/packages/theme/src/mixins.ts: Unexpected token (25:7)

  23 |     name,
  24 |     definition: animationDef,
> 25 |   } as const
     |        ^
  26 | }
  27 | 
  28 | const createCssDefinitionFromObject = (definition: {
    at Object.raise (/Users/hotell/Projects/devel/twisto/twisto-ui/node_modules/@babel/parser/lib/index.js:3831:17)
    at Object.unexpected (/Users/hotell/Projects/devel/twisto/twisto-ui/node_modules/@babel/parser/lib/index.js:5143:16)
    at Object.tsParseNonArrayType (/Users/hotell/Projects/devel/twisto/twisto-ui/node_modules/@babel/parser/lib/index.js:9269:16)
    at Object.tsParseArrayTypeOrHigher (/Users/hotell/Projects/devel/twisto/twisto-ui/node_modules/@babel/parser/lib/index.js:9273:21)
    at Object.tsParseTypeOperatorOrHigher (/Users/hotell/Projects/devel/twisto/twisto-ui/node_modules/@babel/parser/lib/index.js:9312:120)
    at Object.tsParseUnionOrIntersectionType (/Users/hotell/Projects/devel/twisto/twisto-ui/node_modules/@babel/parser/lib/index.js:9317:16)
    at Object.tsParseIntersectionTypeOrHigher (/Users/hotell/Projects/devel/twisto/twisto-ui/node_modules/@babel/parser/lib/index.js:9335:17)
    at Object.tsParseUnionOrIntersectionType (/Users/hotell/Projects/devel/twisto/twisto-ui/node_modules/@babel/parser/lib/index.js:9317:16)
    at Object.tsParseUnionTypeOrHigher (/Users/hotell/Projects/devel/twisto/twisto-ui/node_modules/@babel/parser/lib/index.js:9339:17)
    at Object.tsParseNonConditionalType (/Users/hotell/Projects/devel/twisto/twisto-ui/node_modules/@babel/parser/lib/index.js:9492:17)
```

## Solution

after manually bumping linaria dependencies to latest, issue is resolved  as expected,
**although I would prefer to consume users babel config for transforms** 👉 https://github.com/callstack/linaria/blob/master/src/transform.js#L64

```diff
    "@babel/core": "^7.3.3",
    "@babel/core": "^7.4.4",
    "@babel/generator": "^7.4.4",
    "@babel/plugin-proposal-export-namespace-from": "^7.2.0",
    "@babel/plugin-syntax-dynamic-import": "^7.2.0",
    "@babel/plugin-transform-modules-commonjs": "^7.2.0",
    "@babel/register": "^7.4.4",
```

**Comment by Hotell** [comment]
@pbitkowski it's not very cool to change issues titles which you don't own. Anyone trying to find this particular issue while running into problem with TS and linaria would probably never look solution within issue with title: `update: to babel 7.4`

**Comment by thymikee** [comment]
@Hotell as long as the error message is somewhere in the issue text that shouldn't be a problem for indexing bots, isn't it? I'm sure @pbitkowski had good intentions and did that to ease working with the issues we have in store. Sorry if it was too intrusive

**Comment by Hotell** [comment]
@thymikee yes that's correct. I would suggest to rather create appropriate flags, than renaming issues in long run, as in my experience, it's not very nice to contributors (personally I don't mind, but you never know who is on the other side of the line 👀)

**Comment by thymikee** [comment]
Sure we'll take that into account 👍

**Comment by ShanonJackson** [comment]
Can we please upgrade core-js as a dependency? its causing inter-dependency issues in my project between other libraries who rely on the latest version of core-js.

**Comment by jayu** [comment]
We currently use babel `7.9`
