### ISSUE TITLE
[1.4.0-alpha.0] Incompatible with @babel/preset-typescript

### ISSUE THREAD

**Issue by kryops** [callstack/linaria#428]
## Environment

I have a TypeScript project that I build through webpack > babel-loader > @babel/preset-typescript

## Description

```
ERROR in ./frontend/src/index.tsx
[1] Module build failed (from ./node_modules/babel-loader/lib/index.js):
[1] Error: [BABEL] unknown: Configuration contains string/RegExp pattern, but no filename was passed to Babel (While processing: "<project>/node_modules/linaria/babel.js")
[1]     at matchPattern (<project>/node_modules/@babel/core/lib/config/config-chain.js:431:11)
[1]     at patterns.some.pattern (<project>/node_modules/@babel/core/lib/config/config-chain.js:418:35)
[1]     at Array.some (<anonymous>)
[1]     at matchesPatterns (<project>/node_modules/@babel/core/lib/config/config-chain.js:418:19)
[1]     at configFieldIsApplicable (<project>/node_modules/@babel/core/lib/config/config-chain.js:400:10)
[1]     at configIsApplicable (<project>/node_modules/@babel/core/lib/config/config-chain.js:395:41)
[1]     at forEach (<project>/node_modules/@babel/core/lib/config/config-chain.js:256:13)
[1]     at Array.forEach (<anonymous>)
[1]     at <project>/node_modules/@babel/core/lib/config/config-chain.js:253:42
[1]     at buildPresetChain (<project>/node_modules/@babel/core/lib/config/config-chain.js:45:17)
[1]     at loadPresetDescriptor (<project>/node_modules/@babel/core/lib/config/full.js:235:44)
[1]     at config.presets.reduce (<project>/node_modules/@babel/core/lib/config/full.js:77:21)
[1]     at Array.reduce (<anonymous>)
[1]     at recurseDescriptors (<project>/node_modules/@babel/core/lib/config/full.js:74:38)
[1]     at loadFullConfig (<project>/node_modules/@babel/core/lib/config/full.js:108:6)
[1]     at parseSync (<project>/node_modules/@babel/core/lib/parse.js:50:38)
[1]     at Object.<anonymous> (<project>/node_modules/linaria/src/babel/evaluate/shaker.ts:61:14)
[1]     at Module._compile (<project>/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
[1]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
[1]     at Module.load (internal/modules/cjs/loader.js:685:32)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:620:12)
[1]     at Module.require (internal/modules/cjs/loader.js:723:19)
[1]     at require (<project>/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
[1]     at Object.<anonymous> (<project>/node_modules/linaria/src/babel/extract.ts:6:1)
```

Babel is looking for `context.filename` to match it against the `.ts` pattern, but `context` only contains

```
{
  "cwd": "<project>",
  "root": "<project>",
  "envName": "development"
}
```

The code in linaria's `shaker.ts` is

```
const file = parseSync(`
  fn => {
    try {
      return fn();
    } catch (e) {
      return e;
    }
  };
`) as t.File;
```

Adding something like `{ filename: 'foobar' }` as second argument seems to fix the problem.

## Reproducible Demo

https://github.com/kryops/linaria-babel-typescript

**Comment by satya164** [comment]
cc @Anber

**Comment by thymikee** [comment]
Fixed in `alpha.1`
