### ISSUE TITLE
Babel error when declaring and styling class components in the same file

### ISSUE THREAD

**Issue by silvenon** [callstack/linaria#469]
## Environment

```
linaria@1.3.1
@babel/preset-env@7.5.5
@babel/preset-react@7.0.0
```

## Description

If a class component is declared in the same file as it's being styled with `styled`, it causes the following error:

```
TypeError: Property declarations[0] of VariableDeclaration expected node to be of a type ["VariableDeclarator"] but instead got "ClassDeclaration"
    at validate (/Users/silvenon/Code/test/linaria/node_modules/@babel/types/lib/definitions/utils.js:131:13)
    at validator (/Users/silvenon/Code/test/linaria/node_modules/@babel/types/lib/definitions/utils.js:100:7)
    at Object.validate (/Users/silvenon/Code/test/linaria/node_modules/@babel/types/lib/definitions/utils.js:201:7)
    at validateField (/Users/silvenon/Code/test/linaria/node_modules/@babel/types/lib/validators/validate.js:22:9)
    at validate (/Users/silvenon/Code/test/linaria/node_modules/@babel/types/lib/validators/validate.js:16:3)
    at builder (/Users/silvenon/Code/test/linaria/node_modules/@babel/types/lib/builders/builder.js:46:27)
    at Object.VariableDeclaration (/Users/silvenon/Code/test/linaria/node_modules/@babel/types/lib/builders/generated/index.js:427:31)
    at resolve (/Users/silvenon/Code/test/linaria/node_modules/linaria/lib/babel/evaluate.js:80:22)
    at evaluate (/Users/silvenon/Code/test/linaria/node_modules/linaria/lib/babel/evaluate.js:114:5)
    at TaggedTemplateExpression (/Users/silvenon/Code/test/linaria/node_modules/linaria/lib/babel/visitors/TaggedTemplateExpression.js:257:46)
```

## Reproducible Demo

Install `core-js` 2 to avoid #468 and install Babel CLI:

```
yarn add core-js@^2 @babel/cli
```

Configure Babel:

```js
module.exports = {
  presets: [
    'linaria/babel',
    '@babel/preset-env',
    '@babel/preset-react',
  ],
}
```

Define a class component and style it with Linaria:

```jsx
import React from 'react'
import { styled } from 'linaria/react'

class MyComp extends React.Component {
  render() {
    return <div {...this.props} />
  }
}

const StyledMyComp = styled(MyComp)`
  background: purple;
`
```

Try to compile the code with Babel CLI:

```
yarn babel index.js
```

**Comment by jayu** [comment]
could not repro with `1.4.0-beta.5`
