### ISSUE TITLE
NextJS + Lerna + Linaria - Current solutions for sibling import fail.

### ISSUE THREAD

**Issue by mikestopcontinues** [callstack/linaria#587]
## Environment

General strategy:
I'm using Lerna to (theoretically) easily share code between a handful of related apps. Though I have major issues with Next, it's still the best way to get pre-rendering and static rendering, so I'm using it for all of the apps. And I'm using Linaria because it's the best damn css-in-js solution out there. (Although whereas I can get Astroturf or Styled-Components working with this setup, I'm having a hell of a time with Linaria.)

As it stands, I can share lots of theme-related code, including my template literal helper functions. But when I try to import files that have css blocks in them from sibling libraries, things fall apart.

Versions:
- Linaria version: 1.4.0-beta.6
- Lerna: 3.20.2, with npm, hoisting everything
- Webpack: 4.43.0
- Babel: 7.8.3
- NextJS: 9.3.5, using next-transpile-modules and next-css, not built-in css
- Node.js version: 13.10.1
- OSX: 10.15.3

## Description

I'm trying to import shared css and shared components from sibling packages, but doing so results in transpilation errors. For example, `@arc/view-app` tries to import `@arc/theme/components/Typo` symlinked at `./node_modules/@arc/theme`, but gets:

```
[ error ] ./node_modules/@arc/theme/components/Typo.js
<path>/arc/apps/view-app/node_modules/@arc/theme/components/Typo.js:2
import { css, cx } from 'linaria';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at transformFile.next (<anonymous>)
ModuleBuildError: Module build failed (from <path>/arc/node_modules/linaria/loader.js):
<path>/arc/apps/view-app/node_modules/@arc/theme/components/Typo.js:2
import { css, cx } from 'linaria';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at new Script (vm.js:96:7)
    at Module.evaluate (<path>/arc/node_modules/linaria/lib/babel/module.js:258:20)
    at evaluate (<path>/arc/node_modules/linaria/lib/babel/evaluators/index.js:14:5)
    at PluginPass.enter (<path>/arc/node_modules/linaria/lib/babel/extract.js:105:56)
    at newFn (<path>/arc/node_modules/@babel/traverse/lib/visitors.js:179:21)
    at NodePath._call (<path>/arc/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (<path>/arc/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (<path>/arc/node_modules/@babel/traverse/lib/path/context.js:90:31)
    at TraversalContext.visitQueue (<path>/arc/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitSingle (<path>/arc/node_modules/@babel/traverse/lib/context.js:84:19)
    at TraversalContext.visit (<path>/arc/node_modules/@babel/traverse/lib/context.js:140:19)
    at Function.traverse.node (<path>/arc/node_modules/@babel/traverse/lib/index.js:84:17)
    at traverse (<path>/arc/node_modules/@babel/traverse/lib/index.js:66:12)
    at transformFile (<path>/arc/node_modules/@babel/core/lib/transformation/index.js:107:29)
    at transformFile.next (<anonymous>)
    at run (<path>/arc/node_modules/@babel/core/lib/transformation/index.js:35:12)
    at <path>/arc/node_modules/next/node_modules/webpack/lib/NormalModule.js:316:20
    at <path>/arc/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at <path>/arc/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at runSyncOrAsync (<path>/arc/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (<path>/arc/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at <path>/arc/node_modules/loader-runner/lib/LoaderRunner.js:205:4
    at <path>/arc/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:85:15
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

This is what my webpack rules look like after everything:

```js
[
  {
    test: /\.(tsx|ts|js|mjs|jsx)$/,
    include: [
      '/Users/msc/Code/sitearcade/apps/view-app',
      /next[\\/]dist[\\/]next-server[\\/]lib/,
      /next[\\/]dist[\\/]client/,
      /next[\\/]dist[\\/]pages/,
      /[\\/](strip-ansi|ansi-regex)[\\/]/
    ],
    exclude: [Function: exclude],
    use: { loader: 'next-babel-loader', options: [Object] }
  },
  {
    oneOf: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ]
  },
  { test: /\.svg$/, use: [ [Object], [Object] ] },
  {
    test: /\.ya?ml$/,
    use: { loader: 'js-yaml-loader', options: [Object] }
  },
  {
    test: /\.+(js|jsx|mjs|ts|tsx)$/,
    loader: { loader: 'next-babel-loader', options: [Object] },
    include: [ /(@arc)$/, /(@arc)[\\/](?!.*node_modules)/ ]
  },
  { test: /\.css$/, use: [ 'ignore-loader' ] },
  { test: /\.([jt]sx?|mjs)$/, use: [ {
    loader: 'linaria/loader',
    options: {
      evaluate: true,
      displayName: !isProd,
      sourceMap: !isProd,
      ignore: /node_modules\/(?!@arc)/,
      babelOptions: {
        rootMode: 'upward',
      },
    },
  } ] }
]
```

## Reproducible Demo

I've tried to encompass a selection of different import pathways to ensure solving one import doesn't break another.

https://github.com/mikestopcontinues/lerna-next-linaria

Thanks!

**Comment by jayu** [comment]
Hi, thanks for the verbose description, it's always nice to have that kind of issues :D.
I didn't look into your reproduction yet, but I can see the possible reason why it throws an error. 

It looks like your files were not transpiled because there is an `import` statement instead of require. 
Your ignore statement in the config should force linaria to transpile your `@arc/something` modules, but this option was broken and get fixed recently #575, #579. Tomorrow I will release `1.4.0-beta.7` that will include this fix.

**Comment by mikestopcontinues** [comment]
Thanks @jayu ! That sounds spot on. I'll keep an eye out for the patch :)

**Comment by jayu** [comment]
@mikestopcontinues Done ;)

**Comment by mikestopcontinues** [comment]
Works like a charm! Thanks!
