### ISSUE TITLE
extractor fails with newer babel helpers transforms

### ISSUE THREAD

**Issue by redbugz** [callstack/linaria#758]
## Environment

"@babel/helper-module-transforms": "7.14",
"@babel/helpers": "7.14"

- Linaria version: 1.4.1, extractor 3.0.0-beta.1
- Bundler (+ version): webpack 4.43.0
- Node.js version: 14.16.1
- OS: Linux

## Description

Starting with 7.14.0 of @babel/helpers and @babel/helper-modulel-transforms we get an compilation error with linaria. If I revert back to 7.13 the error goes away, so it appears babel has changed their transforms in a way that is breaking the linaria extractor

```
@myscope/my-module: Error: /mnt/work/dev/my-project/packages/my-package/src/SomeComponent.js: An unexpected runtime error ocurred during dependencies evaluation: 
@myscope/my-module: /mnt/work/dev/my-project/packages/my-package/src/SomeComponent.js:8
@myscope/my-module:       var _AnotherComponent = _interopRequireWildcard(require("./AnotherComponent"));
@myscope/my-module:                                       ^
@myscope/my-module: TypeError: _interopRequireWildcard is not a function
@myscope/my-module:     at /mnt/work/dev/my-project/packages/my-package/src/SomeComponent.js:8:39
@myscope/my-module:     at /mnt/work/dev/my-project/packages/my-package/src/SomeComponent.js:94:3
@myscope/my-module:     at Script.runInContext (vm.js:143:18)
@myscope/my-module:     at Module.evaluate (/mnt/work/dev/my-project/node_modules/linaria/lib/babel/module.js:284:12)
@myscope/my-module:     at Module.evaluate (/mnt/work/dev/my-project/node_modules/linaria/lib/babel/module.js:284:12)
@myscope/my-module:     at evaluate (/mnt/work/dev/my-project/node_modules/linaria/lib/babel/evaluators/index.js:18:5)
@myscope/my-module:     at PluginPass.enter (/mnt/work/dev/my-project/node_modules/linaria/lib/babel/extract.js:146:58)
@myscope/my-module:     at newFn (/mnt/work/dev/my-project/node_modules/@babel/traverse/lib/visitors.js:175:21)
@myscope/my-module:     at NodePath._call (/mnt/work/dev/my-project/node_modules/@babel/traverse/lib/path/context.js:55:20)
@myscope/my-module:     at NodePath.call (/mnt/work/dev/my-project/node_modules/@babel/traverse/lib/path/context.js:42:17)
@myscope/my-module:     at NodePath.visit (/mnt/work/dev/my-project/node_modules/@babel/traverse/lib/path/context.js:92:31)

```
Logging out the transformed code, it looks like tihs:
```
@myscope/my-module:   var _typeof = require("@babel/runtime/helpers/typeof");
@myscope/my-module:   {
@myscope/my-module:     var _src2 = require("../../ui/src");
@myscope/my-module:     {
@myscope/my-module:       var _AnotherComponent = _interopRequireWildcard(require("./AnotherComponent"));
@myscope/my-module:       {
@myscope/my-module:         function _getRequireWildcardCache(nodeInterop) {
@myscope/my-module:           if (typeof WeakMap !== "function") return null;
@myscope/my-module:           var cacheBabelInterop = new WeakMap();
@myscope/my-module:           var cacheNodeInterop = new WeakMap();
@myscope/my-module:           return (_getRequireWildcardCache = function _getRequireWildcardCache(nodeInterop) {
@myscope/my-module:             return nodeInterop ? cacheNodeInterop : cacheBabelInterop;
@myscope/my-module:           })(nodeInterop);
@myscope/my-module:         }
@myscope/my-module:         {
@myscope/my-module:           function _interopRequireWildcard(obj, nodeInterop) {
@myscope/my-module:             if (!nodeInterop && obj && obj.__esModule) {
@myscope/my-module:               return obj;
@myscope/my-module:             }
@myscope/my-module:             if (obj === null || _typeof(obj) !== "object" && typeof obj !== "function") {
@myscope/my-module:               return {
@myscope/my-module:                 "default": obj
@myscope/my-module:               };
@myscope/my-module:             }
@myscope/my-module:             var cache = _getRequireWildcardCache(nodeInterop);
@myscope/my-module:             if (cache && cache.has(obj)) {
@myscope/my-module:               return cache.get(obj);
@myscope/my-module:             }
```
You can see that _interopRequireWildcard is called before it's declared, in the babel code without linaria, it is also called before it's declared, but it's in the same scope so it works, but above, since it's in a new code block, it can't resolve the function declaration below it. There is a new typeof helper added, not sure if that is related or not.

## Reproducible Demo

I am working on a unit test snapshot, here is what I have from my WIP so far:

```
exports[`shakes imports with default and named exports 1`] = `
"{
  var _ = _interopRequireWildcard(require(\\"\\\\u2026\\"));

  {
    var _2 = _interopRequireWildcard(require(\\"\\\\u20262\\"));

    {
      function _getRequireWildcardCache(nodeInterop) {
        if (typeof WeakMap !== \\"function\\") return null;
        var cacheBabelInterop = new WeakMap();
        var cacheNodeInterop = new WeakMap();
        return (_getRequireWildcardCache = function (nodeInterop) {
          return nodeInterop ? cacheNodeInterop : cacheBabelInterop;
        })(nodeInterop);
      }

      {
        function _interopRequireWildcard(obj, nodeInterop) {
          if (!nodeInterop && obj && obj.__esModule) {
            return obj;
          }

          if (obj === null || typeof obj !== \\"object\\" && typeof obj !== \\"function\\") {
            return {
              default: obj
            };
          }

          var cache = _getRequireWildcardCache(nodeInterop);

          if (cache && cache.has(obj)) {
            return cache.get(obj);
          }

          var newObj = {};
          var hasPropertyDescriptor = Object.defineProperty && Object.getOwnPropertyDescriptor;

          for (var key in obj) {
            if (key !== \\"default\\" && Object.prototype.hasOwnProperty.call(obj, key)) {
              var desc = hasPropertyDescriptor ? Object.getOwnPropertyDescriptor(obj, key) : null;

              if (desc && (desc.get || desc.set)) {
                Object.defineProperty(newObj, key, desc);
              } else {
                newObj[key] = obj[key];
              }
            }
          }

          newObj.default = obj;

          if (cache) {
            cache.set(obj, newObj);
          }

          return newObj;
        }

        {
          exports.__linariaPreval = [_.color, _.default, _2.someConst];
        }
      }
    }
  }
}"
`;
```

The changes to the babel transforms seem to focus around using default and named exports together in a single import, at least that is the scenario that started failing for us
import SomeDefault, { someValue } from 'my-module'

and then using someValue in a css block. If I change it to:
import { SomeDefault, someValue} from 'my-module' and change SomeDefault from a default export to a named export then the problem goes away because babel transforms it differently.

**Comment by Anber** [comment]
`extractor` strategy is deprecated. Everything should work fine with `shaker`, that is the default strategy since 2.0.
