### ISSUE TITLE
linaria/shaker: results are not consistent on Windows vs Linux

### ISSUE THREAD

**Issue by layershifter** [callstack/linaria#796]
## Environment

- Linaria version: @linaria/babel@3.0.0-beta.0, @linaria/shaker@3.0.0-beta.5
- Node.js version: v12.19.0 (on both)
- OS: Windows 10, Ubuntu 20.04 LTS on WSL

## Description

Hey folks, we are using `@linaria/babel` & `@linaria/shaker` in our own Babel plugin for CSS-in-JS, thanks for your work ♥

Recently we enabled `@linaria/shaker` and it worked perfectly until we received a report that it breaks build on Windows https://github.com/microsoft/fluentui/issues/18801:

```
ERR! [12:54:17 PM] x office-ui-fabric-react\packages\react-button\lib-commonjs\components\CompoundButton\useCompoundButtonStyles.js:35
ERR!     padding: useButtonStyles_1.buttonSpacing.medium
ERR!                                              ^
ERR!
ERR! TypeError: Cannot read property 'medium' of undefined
ERR!     at office-ui-fabric-react\packages\react-button\
src\components\CompoundButton\useCompoundButtonStyles.ts:35:11
ERR!     at office-ui-fabric-react\packages\react-button\
lib-commonjs\components\CompoundButton\useCompoundButtonStyles.js:214:3
ERR!     at Script.runInContext (vm.js:130:18)
ERR!     at Module.evaluate (office-ui-fabric-react\node_modules\@linaria\babel\src\module.ts:310:12)
ERR!     at evaluate (office-ui-fabric-react\packages\babel-make-styles\lib\src\utils\evaluatePathsInVM.js:29:9)
```

Surprisingly, CI builds were passing and works on Linux machines 😲

I added additional logging to `shaker/index.ts`:

https://github.com/callstack/linaria/blob/e92bcd93ed51b847cab0c9e3fa7c578328c1ddaf/packages/shaker/src/index.ts#L60-L62

And results for Windows & Linux are different 😐

<details>
  <summary>Linux output</summary>

```
2021-07-02T09:52:47.968Z linaria:evaluator:shaker:generate  Generate shaken source code fluentui/packages/react-button/lib-commonjs/components/Button/useButtonStyles.js
2021-07-02T09:52:47.975Z linaria:evaluator:shaker:generate  Shaken code:"use strict";

        var _makeStyles = require("@fluentui/make-styles");

        var _theme = (_makeStyles.createCSSVariablesProxy)();

        Object.defineProperty(exports, "__esModule", {
          value: true
        });
```
</details>

<details>
  <summary>Windows output</summary>

```
2021-07-02T09:54:59.098Z linaria:evaluator:shaker:generate  Generate shaken source code office-ui-fabric-react\packages\react-button\lib-commonjs\components\Button\useButtonStyles.js
2021-07-02T09:54:59.099Z linaria:evaluator:shaker:generate  Shaken code:
2021-07-02T09:54:59.099Z linaria:sub-module-1:evaluate 
```
</details>

AST output is also different 🙄

<details>
  <summary>Linux output</summary>

```
2021-07-02T09:52:47.966Z linaria:evaluator:shaker:shake
        Program ✅
        |-directives
        | 0=Directive ✅
        | | |-value
        | | | |=DirectiveLiteral ✅
        |-body
```
</details>

<details>
  <summary>Windows output</summary>

```
2021-07-02T09:54:59.098Z linaria:evaluator:shaker:shake  
	Program ❌
	|-directives
	| 0=Directive ❌
	| | |-value
	| | | |=DirectiveLiteral ❌
	|-body
```
</details>

## Reproducible Demo

I am working on it 🧐

**Comment by layershifter** [comment]
Huh, it was an issue with regex 😅 I used following rules:

```
      { action: shakerEvaluator },
      {
        test: /node_modules/,
        action: 'ignore',
      },
```

And this worked well for Linux, but on Windows we always evaluated shaker 😕 A fix is to modify regex to `/[/\\]node_modules[/\\]/` 🎉

---

https://github.com/microsoft/fluentui/pull/18816
