### ISSUE TITLE
styled doesn't work on ESM format component but CommonJS format component 

### ISSUE THREAD

**Issue by zheeeng** [callstack/linaria#859]
## Environment

- Linaria version: 
        "@linaria/core": "3.0.0-beta.4",
        "@linaria/react": "3.0.0-beta.7",
        "@linaria/shaker": "3.0.0-beta.7",
- Bundler (+ version): vite(2.3.5)
- Node.js version: v14.17.0
- OS: MacOS

## Description

styled doesn't work on ESM format component but CommonJS format component 

## Reproducible Demo

```ts
import React, { FC } from 'react'
import { styled } from '@linaria/react'
import Button from 'antd/lib/button'
import Button2 from 'antd/es/button'
import 'antd/es/button/style/css'

import { theme } from '../ui/theme'

interface Props {}

const StyledButton = styled(Button)`
  width: 500px;
`
const StyledButton2 = styled(Button2)`
  width: 500px;
`

export const Test: FC<Props> = ({}) => {
  return <div>
    <StyledButton>Test</StyledButton>
    <StyledButton2>Test</StyledButton2>
  </div>
}
```

StyledButton2 reports：

```ts
[plugin:vite-plugin-linaria-styled] /Users/zheeeng/Workspace/vite-linaria-effector-boilerplate/src/components/Test.tsx: An unexpected runtime error occurred during dependencies evaluation: 
/Users/zheeeng/Workspace/vite-linaria-effector-boilerplate/node_modules/antd/es/button/index.js:1
(function (exports) { import Button from './button';
                      ^^^^^^

SyntaxError: Cannot use import statement outside a module
    at new Script (vm.js:88:7)
    at Module.evaluate (/Users/zheeeng/Workspace/vite-linaria-effector-boilerplate/node_modules/@linaria/babel-preset/lib/module.js:290:20)
    at Module.Object.assign.ensure (/Users/zheeeng/Workspace/vite-linaria-effector-boilerplate/node_modules/@linaria/babel-preset/lib/module.js:197:15)
    at /Users/zheeeng/Workspace/vite-linaria-effector-boilerplate/src/components/Test.tsx:11:39
    at /Users/zheeeng/Workspace/vite-linaria-effector-boilerplate/src/components/Test.tsx:30:3
    at Script.runInContext (vm.js:130:18)
    at Module.evaluate (/Users/zheeeng/Workspace/vite-linaria-effector-boilerplate/node_modules/@linaria/babel-preset/lib/module.js:293:12)
    at evaluate (/Users/zheeeng/Workspace/vite-linaria-effector-boilerplate/node_modules/@linaria/babel-preset/lib/evaluators/index.js:18:5)
    at PluginPass.enter (/Users/zheeeng/Workspace/vite-linaria-effector-boilerplate/node_modules/@linaria/babel-preset/lib/extract.js:148:58)
    at newFn (/Users/zheeeng/Workspace/vite-linaria-effector-boilerplate/node_modules/@babel/traverse/lib/visitors.js:171:21)

It may happen when your code or third party module is invalid or uses identifiers not available in Node environment, eg. window. 
Note that line numbers in above stack trace will most likely not match, because Linaria needed to transform your code a bit.
```

**Comment by Anber** [comment]
By default, Linaria imports everything from node_modules as it is. If you want to use es-modules, you have to add a rule for folders with es-modules to the configuration https://github.com/callstack/linaria/blob/master/docs/CONFIGURATION.md#options
```
[
  {
    action: require('@linaria/shaker').default,
  },
  {
    test: /\/node_modules\//,
    action: 'ignore',
  },
  {
    test: /\/node_modules\/antd\/es\//,
    action: require('@linaria/shaker').default,
  },
];
```
