### ISSUE TITLE
Error when styling a React component imported from another file

### ISSUE THREAD

**Issue by jonrimmer** [callstack/linaria#885]
## Environment

- Linaria version: 3.0.0-beta.15
- Bundler (+ version): ESBuild 0.14.3
- Node.js version: v16.13.0
- OS: macOS 11.16

## Description

I have a setup a very simple esbuild/linaria build [as per the documentation](https://github.com/callstack/linaria/blob/master/docs/BUNDLERS_INTEGRATION.md#esbuild) but it is not working.

If I have a React component defined in one file, like this:

```tsx
export const Button: FC<{ className?: string; style?: CSSProperties }> = ({ children, className, style }) => (
  <button className={className} style={style}>
    {children}
  </button>
);
```

And I try to import it in another file and style it using Linaria:

```tsx
import { Button } from "./Button";
import { styled } from "@linaria/react";

const StyledButton = styled(Button)``;
```

Linaria errors during the build with the following:

```
✘ [ERROR] [plugin linaria] /code/linaria-esbuild/src/App.tsx: An unexpected runtime error occurred during dependencies evaluation:
/code/linaria-esbuild/node_modules/@babel/core/lib/parser/index.js:93
    throw err;
    ^

SyntaxError: /code/linaria-esbuild/src/Button.tsx: 'Const declarations' require an initialization value. (3:19)

  1 | import { CSSProperties, FC } from "react";
  2 |
> 3 | export const Button: FC<{ className?: string; style?: CSSProperties }> = ({
    |                    ^
  4 |   children,
  5 |   className,
  6 |   style,
    at Parser._raise (/code/linaria-esbuild/node_modules/@babel/parser/lib/index.js:541:17)
    at Parser.raiseWithData (/code/linaria-esbuild/node_modules/@babel/parser/lib/index.js:534:17)
    at Parser.raise (/code/linaria-esbuild/node_modules/@babel/parser/lib/index.js:495:17)
    at Parser.parseVar (/code/linaria-esbuild/node_modules/@babel/parser/lib/index.js:14026:18)
    at Parser.parseVarStatement (/code/linaria-esbuild/node_modules/@babel/parser/lib/index.js:13836:10)
    at Parser.parseStatementContent (/code/linaria-esbuild/node_modules/@babel/parser/lib/index.js:13421:21)
    at Parser.parseStatement (/code/linaria-esbuild/node_modules/@babel/parser/lib/index.js:13352:17)
    at Parser.parseExportDeclaration (/code/linaria-esbuild/node_modules/@babel/parser/lib/index.js:14594:17)
    at Parser.maybeParseExportDeclaration (/code/linaria-esbuild/node_modules/@babel/parser/lib/index.js:14550:31)
    at Parser.parseExport (/code/linaria-esbuild/node_modules/@babel/parser/lib/index.js:14477:29)
```

## Reproducible Demo

https://github.com/jonrimmer/linaria-esbuild

Run:

```
npm install
npm run build
```

**Comment by jonrimmer** [comment]
Closing this. I didn't realise Linaria needs to run its own internal Babel instance to parse the whole codebase. For anyone who encounters the same, the "solution" was to add `@babel/preset-react`, `@babel/preset-typescript` to the `babelOptions` of the Linaria esbuild plugin.

Although I actually decided to switch back to styled-components, as the effect of adding a full Babel run into our Storybook, vite, etc. build wasn't worth it.
