### ISSUE TITLE
Webpack issues in linaria@2.3.0

### ISSUE THREAD

**Issue by dcousineau-godaddy** [callstack/linaria#892]
## Environment

- Linaria version: 2.3.0
- Bundler (+ version): webpack@4.46.0
- Node.js version: 14.17.0
- OS: macOS 11.6.1

## Description

This issue is partially if not wholly duplicative of #891, however I am re-filing to indicate that the `linaria@2.3.0` release is affected and is not isolated to the beta branch.

When our local dev environments picked up `linaria@2.3.0` we started receiving build errors:

```
ERROR in ../button/src/styles.js (/path/to/project/node_modules/@storybook/react/node_modules/css-loader/dist/cjs.js??ref--7-1!/path/to/project/node_modules/postcss-loader/src??postcss!/path/to/project/node_modules/linaria/lib/outputCssLoader.js?cacheProvider=undefined!../button/src/styles.js)
Module build failed (from /path/to/project/node_modules/linaria/lib/outputCssLoader.js):
Error: Cannot find module 'undefined'
Require stack:
- /path/to/project/node_modules/linaria/lib/cache.js
- /path/to/project/node_modules/linaria/lib/loader.js
- /path/to/project/node_modules/linaria/loader.js
- /path/to/project/node_modules/loader-runner/lib/loadLoader.js
- /path/to/project/node_modules/loader-runner/lib/LoaderRunner.js
- /path/to/project/node_modules/webpack/lib/NormalModule.js
- /path/to/project/node_modules/webpack/lib/NormalModuleFactory.js
- /path/to/project/node_modules/webpack/lib/Compiler.js
- /path/to/project/node_modules/webpack/lib/webpack.js
- /path/to/project/node_modules/@storybook/react/node_modules/@storybook/core/dist/server/build-static.js
- /path/to/project/node_modules/@storybook/react/node_modules/@storybook/core/server.js
- /path/to/project/node_modules/@storybook/react/dist/server/index.js
- /path/to/project/node_modules/@storybook/react/bin/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at getCacheInstance (/path/to/project/node_modules/linaria/lib/cache.js:44:12)
    at Object.outputCssLoader (/path/to/project/node_modules/linaria/lib/outputCssLoader.js:19:31)
 @ ../button/src/styles.js (../button/src/styles.linaria.css = /path/to/project/node_modules/linaria/lib/outputCssLoader.js?cacheProvider=undefined!../button/src/styles.js) 2:14-268 21:1-42:3 22:19-273
 @ ../button/src/styles.js
 @ ./examples/.setup/uxcore2.js
 @ ./examples/dismissible.js
 @ ./examples sync nonrecursive ^\.\/([-\w]+)\.js$
 @ /path/to/project/node_modules/@exemplar/storybook-react/load-examples.js
 @ multi /path/to/project/node_modules/@storybook/react/node_modules/@storybook/core/dist/server/common/polyfills.js /path/to/project/node_modules/@storybook/react/node_modules/@storybook/core/dist/server/preview/globals.js /path/to/project/node_modules/@exemplar/storybook-react/load-examples.js (webpack)-hot-middleware/client.js?reload=true&quiet=true
```

**However** we are noticing that rolling back to `linaria@2.2.0` and `linaria@2.1.1` don't seem to be fixing the issue. We will update this report as we start rolling back other packages to see if we can't isolate the issue.

## Reproducible Demo

We do not have a demo at this time but will assist in creating one if necessary / helpful. It's possible the reproduction in #891 is sufficient.

**Comment by malash** [comment]
I believe this issue should be fixed in https://github.com/callstack/linaria/pull/890

**Comment by layershifter** [comment]
Please check with latest versions, a lot of issues have been fixed. If it still happens, please report a new issue and provide details and preferably repro.
