### ISSUE TITLE
_interopRequireDefault is not a function

### ISSUE THREAD

**Issue by SidneyLann** [callstack/linaria#900]
- Linaria version: 3.0.0-beta.1~17
- Bundler (+ version): webpack4.46.0
- Node.js version: 13
- OS: win7

## Description
Module build failed (from ./node_modules/_linaria@3.0.0-beta.17@linaria/lib/webpack4-loader.js):
NonErrorEmittedError: (Emitted value instead of an instance of Error) TypeError: D:\DEV\git\repo_eb\pcng-client-taro-repo\pcng-client-taro\pcng-client-taro\src\componen
t\MessageAlert.tsx: _interopRequireDefault is not a function
    at D:\DEV\git\repo_eb\pcng-client-taro-repo\pcng-client-taro\pcng-client-taro\node_modules\_webpack@4.46.0@webpack\lib\NormalModule.js:313:13
    at D:\DEV\git\repo_eb\pcng-client-taro-repo\pcng-client-taro\pcng-client-taro\node_modules\_loader-runner@2.4.0@loader-runner\lib\LoaderRunner.js:367:11
    at D:\DEV\git\repo_eb\pcng-client-taro-repo\pcng-client-taro\pcng-client-taro\node_modules\_loader-runner@2.4.0@loader-runner\lib\LoaderRunner.js:233:18
    at runSyncOrAsync (D:\DEV\git\repo_eb\pcng-client-taro-repo\pcng-client-taro\pcng-client-taro\node_modules\_loader-runner@2.4.0@loader-runner\lib\LoaderRunner.js:14
3:3)
    at iterateNormalLoaders (D:\DEV\git\repo_eb\pcng-client-taro-repo\pcng-client-taro\pcng-client-taro\node_modules\_loader-runner@2.4.0@loader-runner\lib\LoaderRunner
.js:232:2)
    at Array.<anonymous> (D:\DEV\git\repo_eb\pcng-client-taro-repo\pcng-client-taro\pcng-client-taro\node_modules\_loader-runner@2.4.0@loader-runner\lib\LoaderRunner.js
:205:4)
    at Storage.finished (D:\DEV\git\repo_eb\pcng-client-taro-repo\pcng-client-taro\pcng-client-taro\node_modules\_enhanced-resolve@4.5.0@enhanced-resolve\lib\CachedInpu
tFileSystem.js:55:16)
    at D:\DEV\git\repo_eb\pcng-client-taro-repo\pcng-client-taro\pcng-client-taro\node_modules\_enhanced-resolve@4.5.0@enhanced-resolve\lib\CachedInputFileSystem.js:91:
9
    at D:\DEV\git\repo_eb\pcng-client-taro-repo\pcng-client-taro\pcng-client-taro\node_modules\_graceful-fs@4.2.9@graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
 @ ./src/layout/HeadLayout.tsx 15:0-54 66:32-44

**Comment by zhaoxu-lingoace** [comment]
import pxNormalize from "./pxNormalize";

    width: ${pxNormalize(200)}px;


var _pxNormalize = _interopRequireDefault(require("./pxNormalize"));

TypeError: _interopRequireDefault is not a function
It may happen when your code or third party module is invalid or uses identifiers not available in Node environment, eg. window.
Note that line numbers in above stack trace will most likely not match, because Linaria needed to transform your code a bit.

**Comment by layershifter** [comment]
The issue does not have reproducible case on Stackblitz or Github and will be closed.

v5 has been released recently and fixes a lot of bugs, please bump to it and report a new issue if the problem still exists.
