### ISSUE TITLE
_typeof is not a function

### ISSUE THREAD

**Issue by SidneyLann** [callstack/linaria#905]
Linaria version: 3.0.0-beta.1~17
Bundler (+ version): webpack4.46.0
Node.js version: 13
OS: win7

## Description
 Module build failed (from ./node_modules/_linaria@3.0.0-beta.17@linaria/lib/webpack4-loader.js):
NonErrorEmittedError: (Emitted value instead of an instance of Error) TypeError: D:\DEV\git\repo_eb\pcng-client-taro-repo\pcng-client-taro\pcng-client-taro\src\form\Che
ckBox.tsx: _typeof is not a function
    at D:\DEV\git\repo_eb\pcng-client-taro-repo\pcng-client-taro\pcng-client-taro\node_modules\_webpack@4.46.0@webpack\lib\NormalModule.js:313:13
    at D:\DEV\git\repo_eb\pcng-client-taro-repo\pcng-client-taro\pcng-client-taro\node_modules\_loader-runner@2.4.0@loader-runner\lib\LoaderRunner.js:367:11
    at D:\DEV\git\repo_eb\pcng-client-taro-repo\pcng-client-taro\pcng-client-taro\node_modules\_loader-runner@2.4.0@loader-runner\lib\LoaderRunner.js:233:18
    at runSyncOrAsync (D:\DEV\git\repo_eb\pcng-client-taro-repo\pcng-client-taro\pcng-client-taro\node_modules\_loader-runner@2.4.0@loader-runner\lib\LoaderRunner.js:143:3)
    at iterateNormalLoaders (D:\DEV\git\repo_eb\pcng-client-taro-repo\pcng-client-taro\pcng-client-taro\node_modules\_loader-runner@2.4.0@loader-runner\lib\LoaderRunner.js:232:2)
    at Array.<anonymous> (D:\DEV\git\repo_eb\pcng-client-taro-repo\pcng-client-taro\pcng-client-taro\node_modules\_loader-runner@2.4.0@loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (D:\DEV\git\repo_eb\pcng-client-taro-repo\pcng-client-taro\pcng-client-taro\node_modules\_enhanced-resolve@4.5.0@enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at D:\DEV\git\repo_eb\pcng-client-taro-repo\pcng-client-taro\pcng-client-taro\node_modules\_enhanced-resolve@4.5.0@enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at D:\DEV\git\repo_eb\pcng-client-taro-repo\pcng-client-taro\pcng-client-taro\node_modules\_graceful-fs@4.2.9@graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)

**Comment by jbryant4** [comment]
I am also having this issue

**Comment by jbryant4** [comment]
3.0.0-beta.15

**Comment by SidneyLann** [comment]
I had tried all versions from 3.0.0-beta.1 to 3.0.0-beta.17, all have the problem.
