### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by qiweiii** [callstack/linaria#952]
## Description

When i try to use an imported variables in linaria css, it gives this error, seems to come from @linaria/webpack-loader:

```
/sandbox/node_modules/@ui5/webcomponents-react-base/dist/index.js:1
(function (exports) { import * as Device from './Device';
                      ^^^^^^

SyntaxError: Cannot use import statement outside a module
    at new Script (vm.js:102:7)
    at Module.evaluate (/sandbox/node_modules/@linaria/webpack4-loader/node_modules/@linaria/babel-preset/lib/module.js:290:20)
```

## Reproducible Demo

Please refer to this code sandbox: https://codesandbox.io/s/linaria-demo-forked-1kwhyy?file=/src/App.js

**Comment by qiweiii** [comment]
It seems linaria webpack-loader need to transpile all @ui5 and lit-html packages to ES5

**Comment by meAnurag** [comment]
How can I solve this issue?

**Comment by qiweiii** [comment]
@meAnurag I remember we used a workaround solution: using nodejs to copied the required ui5 file from node_module to our project root on `yarn start` or `yarn build`, so our own project setup will handle its ES6 syntax. This solution is just a workaround and may not apply to your use case since we only need to copy one ES6 file (`ThemeParameters`) from UI5.

**Comment by meAnurag** [comment]
Hey @qiweiii Thanks for the quick response. Actually I am bit confused here. What is a ui5 file? and can you please point me how can I create a workaround like yours.

**Comment by qiweiii** [comment]
@meAnurag in the code sandbox: https://codesandbox.io/s/linaria-demo-forked-1kwhyy?file=/src/App.js, I imported `ThemingParameter` from ui5. For my case this is the line that gives the error, if I remove this import and usage of `ThemingParameter`, the error will be gone. The ui5 file which I refer to is `ThemingParameters.js` which uses ES6 syntax.

So my solution is to maybe add a node script called `copyFiles.js` in my project, it uses nodejs to copy `ThemingParameters.js` from node_modules to the current project. Then in `package.json`'s scripts, we may add `node copyFiles &` infront of the original `start` or `build` script to get `ThemingParameters.js` before my project's transpiling and bundling

**Comment by Anber** [comment]
By default, Linaria doesn't transpile modules inside `node_modules`. However, you can add a rule for a specific folder (see [`rules` options](https://github.com/callstack/linaria/blob/master/docs/CONFIGURATION.md)). For your case, `linaria.config.js` will look like this:
```
module.exports = {
    rules: [
        {
            action: require('@linaria/shaker').default,
        },
        {
            test: /\/node_modules\//,
            action: 'ignore',
        },
        {
            test: /\/node_modules\/@ui5\//,
            action: require('@linaria/shaker').default,
        },
    ]
};
```
