### ISSUE TITLE
Syntax error. Unable to use function with Enum inside styled component

### ISSUE THREAD

**Issue by Gordiann** [callstack/linaria#975]
## Environment

- Linaria version: 3.0.0-beta.18
- Bundler (+ version): Webpack 5.67.0

## Description

When I try to use function getButtonColor inside StyledButton component, syntax error appears.

>ERROR in ./src/ui/Button/style.ts
>Module build failed (from ./node_modules/@linaria/webpack-loader/lib/index.js):
>Error: E:\Web\project\src\ui\Button\style.ts: An unexpected runtime error occurred during dependencies evaluation:
>E:\Web\project\node_modules\@babel\core\lib\parser\index.js:93
 >   throw err;
 >   ^
>
>SyntaxError: E:\Web\project\src\ui\Button\index.tsx: Unexpected token, expected "{" (13:7)
>
>  11 | } from "./style";
> 12 |
> 13 | export enum ButtonKind {
                |        ^
  14 |   PRIMARY = "primary",
  15 |   SUCCESS = "success",
  16 |   WARNING = "warning",
    at instantiate (E:\Web\project\node_modules\@babel\parser\lib\index.js:72:32)
    at constructor (E:\Web\project\node_modules\@babel\parser\lib\index.js:358:12)
    at Object.raise (E:\Web\project\node_modules\@babel\parser\lib\index.js:3334:19)
    at Object.unexpected (E:\Web\project\node_modules\@babel\parser\lib\index.js:3372:16)
    at Object.parseExport (E:\Web\project\node_modules\@babel\parser\lib\index.js:15791:16)
    at Object.parseStatementContent (E:\Web\project\node_modules\@babel\parser\lib\index.js:14644:27)
    at Object.parseStatement (E:\Web\project\node_modules\@babel\parser\lib\index.js:14528:17)
    at Object.parseBlockOrModuleBlockBody (E:\Web\project\node_modules\@babel\parser\lib\index.js:15167:25)
    at Object.parseBlockBody (E:\Web\project\node_modules\@babel\parser\lib\index.js:15158:10)
    at Object.parseProgram (E:\Web\project\node_modules\@babel\parser\lib\index.js:14446:10)

## Reproducible Demo

```
//style.ts

import { css } from "@linaria/core";
import { styled } from "@linaria/react";
import { isNil } from "lodash";
import { ITheme } from "../../theme/theme";
import { ButtonKind } from "./index";

interface IButtonStyleProps extends ITheme {
  kind?: ButtonKind;
}

const getButtonColor = ({ kind, theme }: IButtonStyleProps) => {
  return isNil(kind)
    ? theme.color.primary
    : kind === ButtonKind.SUCCESS
    ? theme.color.success
    : kind === ButtonKind.WARNING
    ? theme.color.warning
    : kind === ButtonKind.DANGER
    ? theme.color.danger
    : theme.color.primary;
};

export const StyledButton = styled.button<IButtonStyleProps>`
  background-color: rgb(${getButtonColor});  
`;
```

```
//index.tsx
//Here is Enum declaration inside index.tsx
export enum ButtonKind {
  PRIMARY = "primary",
  SUCCESS = "success",
  WARNING = "warning",
  DANGER = "danger",
}

```

**Comment by Gordiann** [comment]
Well, it was my mistake. It was necessary to declare enum as const in file index.tsx.
