### ISSUE TITLE
styled API prop interpolation: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by juanferreras** [callstack/linaria#981]
## Environment

- Linaria version: `3.0.0-beta.19`
- Bundler (+ version): `5.51.1`
- Node.js version: `14.18.1`
- OS: macOS/linux 

## Description

This is a regression from `3.0.0-beta.19`, affecting both `@linaria/react` and `@linaria/atomic` `styled` API, when using (any?) dynamic interpolation such as the simplest `color: ${(props) => props.color};`

```
TypeError: /sandbox/src/App.js: Cannot read property '0' of undefined
    at Generator.ArrowFunctionExpression (/sandbox/node_modules/@babel/generator/lib/generators/methods.js:129:33)
    at /sandbox/node_modules/@babel/generator/lib/printer.js:310:19
    at Buffer.withSource (/sandbox/node_modules/@babel/generator/lib/buffer.js:199:5)
    at Generator.withSource (/sandbox/node_modules/@babel/generator/lib/printer.js:176:15)
    at Generator.print (/sandbox/node_modules/@babel/generator/lib/printer.js:309:10)
    at Generator.ArrayExpression (/sandbox/node_modules/@babel/generator/lib/generators/types.js:113:12)
    at /sandbox/node_modules/@babel/generator/lib/printer.js:310:19
    at Buffer.withSource (/sandbox/node_modules/@babel/generator/lib/buffer.js:199:5)
    at Generator.withSource (/sandbox/node_modules/@babel/generator/lib/printer.js:176:15)
    at Generator.print (/sandbox/node_modules/@babel/generator/lib/printer.js:309:10)

```

## Reproducible Demo

I've been trying to put the most minimal reproducible demo, as I'm unsure why tests do seem to pass (could be from `evaluate`?). I'm having some issues running `./website` locally but I think the issue is likely replicable there, provided any dynamic interpolation is added (will confirm!)

- `3.0.0-beta.19` does not apply the color rule: see codesandbox https://codesandbox.io/s/linaria-beta-19-styled-prop-239072?file=/src/App.js
- `3.0.0-beta.18` works as expected: see codesandbox https://codesandbox.io/s/linaria-beta-18-styled-prop-0pqm6x?file=/src/App.js  
  - (EDIT: looks like dependencies of dependencies are resolving quite oddly and sometimes it ends up bringing `.19` dependencies, JFYI in case this sandbox doesn't work as expected, it's from not being able to actually force locking down to `.18`)

No changes in between, only upgrading from .18 to .19 (and using a custom yarn resolution to avoid the issue with `loader-utils v3` (see #977)
 
![CleanShot 2022-06-04 at 18 48 42](https://user-images.githubusercontent.com/8507996/172026506-e18770e6-e8dd-4976-b46d-8a0906e2e614.png)
![CleanShot 2022-06-04 at 18 49 14](https://user-images.githubusercontent.com/8507996/172026517-8151290f-d0f5-421d-82f4-8d520622422f.png)

**Comment by Anber** [comment]
Thank you @juanferreras!

It was a bad idea to use `instanceof` :) Fixed in `beta.20`.
